- share/sql/terrama2/terrama2-data-model-pg.sql
> Adding database model for postgresql

- share/sql/terrama2/terrama2-data-model-pg.sql
Adding format specific tables to data model script
> Adding format specific tables to data model script

- share/sql/terrama2/terrama2-data-model-pg.sql
Removing project concept.
Replacing table specific tables for a JSON column named 'dynamic_metadata' in collector table.
> Removing project concept and using JSON to store dynamic metadata

- src/terrama2/ws/collector/server/CsvParser.cpp
- src/terrama2/ws/collector/server/CsvParser.hpp
- src/unittest/ws/collector/core/TestCollector.cpp
Better test example,
simple csv parser for tests
> Simple csv parser and changes in the test

- build/cmake/CMakeLists.txt
- build/cmake/terrama2_macros.cmake
- src/terrama2/ws/collector/server/Collector.hpp
- src/terrama2/ws/collector/server/CollectorService.cpp
- src/terrama2/ws/collector/server/CollectorService.hpp
- src/terrama2/ws/collector/server/DataSetTimer.hpp
- src/unittest/ws/collector/core/TestCollector.cpp
- src/unittest/ws/collector/core/TestDataset.cpp
- src/unittest/ws/collector/server/TestCollectorService.cpp
Creation of classes DataSetTimer and Collector and some small fixes,
now collectore server is compiling.
> creation of classes DataSetTimer and Collector

- src/terrama2/core/DataManager.cpp
- src/terrama2/core/DataManager.hpp
- src/terrama2/core/DataProviderDAO.cpp
- src/terrama2/core/DataProviderDAO.hpp
- src/terrama2/core/DataSetDAO.cpp
- src/terrama2/core/DataSetDAO.hpp
- src/terrama2/core/Utils.cpp
- src/terrama2/core/Utils.hpp
- src/unittest/core/Utils.cpp
- src/unittest/core/Utils.hpp
- src/unittest/core/main.cpp
Standardizing parameters type
Renaming TestUtils to Utils
Documentation and exception handling
> Documentation and exception handling

- share/terrama2/sql/terrama2-data-model-pg.sql
- share/terrama2/sql/terrama2-pcd-data-model-pg.sql
- src/terrama2/core/DataSetDAO.cpp
- src/unittest/core/TsApplicationController.cpp
- src/unittest/core/TsApplicationController.hpp
- src/unittest/core/TsDataProviderDAO.cpp
- src/unittest/core/TsDataProviderDAO.hpp
- src/unittest/core/TsDataSetDAO.cpp
- src/unittest/core/TsDataSetDAO.hpp
- src/unittest/core/main.cpp
Renaming unittest for core module
Fix persistence of Datasets
Extract DCP tables from data model script
> Renaming unittest for core module

- src/terrama2/ws/collector/client/Client.cpp
- src/terrama2/ws/collector/client/Client.hpp
- src/terrama2/ws/collector/core/WebService.hpp
- src/terrama2/ws/collector/core/WebServiceDataTypes.hpp
- src/terrama2/ws/collector/server/WebService.cpp
Changed gsoap methods to work in synchronous way: Some methods were implemented in a way that the client dont need to wait the server answer, and they should wait for some possible exception.
Implemented WS client methods and improved some variables and methods names
> Changes in mod WS

- src/terrama2/ws/Exception.hpp
- src/terrama2/ws/collector/Exception.hpp
- src/terrama2/ws/collector/client/Client.cpp
- src/terrama2/ws/collector/client/Client.hpp
- src/terrama2/ws/collector/client/Exception.hpp
- src/terrama2/ws/collector/server/WebService.cpp
If a exception occur in during a request to WS TerraMA2, the server will notify the client about the exception and the client will emit an exception.
> Implemented error handling in WebService

- install/install-3rdparty-linux-ubuntu-14.04.sh
- share/terrama2/sql/terrama2-data-model-pg_oneline.sql
- src/terrama2/core/ApplicationController.cpp
- src/terrama2/core/DataManager.cpp
- src/terrama2/core/DataManager.hpp
- src/terrama2/core/DataProviderDAO.cpp
- src/terrama2/core/DataSetDAO.cpp
- src/terrama2/core/DataSetDAO.hpp
- src/terrama2/core/Exception.hpp
- src/unittest/core/TsDataManager.cpp
- src/unittest/core/TsDataManager.hpp
Fixing dependencies build on ubuntu for soap
Refactoring DataManager tests
Creating table storage_metadata
> Refactoring tests

- src/terrama2/core/ApplicationController.cpp
- src/terrama2/core/DataManager.cpp
- src/terrama2/core/DataManager.hpp
- src/terrama2/core/DataSetDAO.cpp
- src/unittest/core/TsApplicationController.cpp
- src/unittest/core/TsApplicationController.hpp
- src/unittest/core/TsDataManager.cpp
- src/unittest/core/TsDataManager.hpp
- src/unittest/core/Utils.cpp
- src/unittest/core/Utils.hpp
- src/unittest/core/data/project.json
> Adding protection to DataManager methods

- build/cmake/CMakeLists.txt
- build/cmake/terrama2_gui_admin/CMakeLists.txt
- resources/unittest/inpe-queimadas.terrama2
- share/terrama2/icons/terrama2/index.theme
- src/terrama2/gui/admin/AdminApp.cpp
- src/terrama2/gui/admin/ServicesDialog.cpp
- src/terrama2/gui/admin/ServicesDialog.hpp
- src/terrama2/gui/admin/ui/AdminAppForm.ui
- Adding function execute and verify connection; 
- Integration SOAP - Manager Service.
> Adding function execute and verify connection and integration SOAP - Manager Service

- build/cmake/CMakeLists.txt
- build/cmake/terrama2_mod_core/CMakeLists.txt
- src/terrama2/collector/Collector.cpp
- src/terrama2/collector/Collector.hpp
- src/terrama2/collector/CollectorFile.cpp
- src/terrama2/collector/CollectorFile.hpp
- src/terrama2/collector/ParserOGR.cpp
- src/terrama2/core/ApplicationController.cpp
- src/unittest/collector/TsCollectorFile.cpp
- src/unittest/collector/TsDataSetTimer.cpp
- src/unittest/collector/TsParserOGR.cpp
- src/unittest/collector/main.cpp
Temporary using Qt to execute datamodel creation script
> Fix for tests, executing sql creation script

- src/terrama2/gui/config/ConfigApp.cpp
- src/terrama2/gui/config/ConfigAppTab.cpp
- src/terrama2/gui/config/ConfigAppTab.hpp
- src/terrama2/gui/config/ConfigAppWeatherGrid.cpp
- src/terrama2/gui/config/ConfigAppWeatherOccurrence.cpp
- src/terrama2/gui/config/ConfigAppWeatherOccurrence.hpp
- src/terrama2/gui/config/ConfigAppWeatherPcd.cpp
- src/terrama2/gui/config/ConfigAppWeatherServer.cpp
- src/terrama2/gui/config/ConfigAppWeatherTab.cpp
> removing useless code;
> some fields not implemented has been disabled;
> removing dataset;
> code review of config modules.
> updating config module

- src/terrama2/core/ApplicationController.cpp
- src/terrama2/gui/admin/AdminApp.cpp
- src/terrama2/gui/admin/ServicesDialog.cpp
Adding function close services;
Merge conflict application controller.
> Adding function close services and merge conflict application controller

- src/terrama2/gui/admin/AdminApp.cpp
- src/terrama2/gui/admin/ServicesDialog.cpp
- src/terrama2/gui/admin/ui/AdminAppForm.ui
> Settings interface Administration

- src/terrama2/collector/Collector.cpp
- src/terrama2/collector/Collector.hpp
- src/terrama2/collector/CollectorFile.cpp
- src/terrama2/collector/CollectorFile.hpp
- src/terrama2/collector/DataProcessor.cpp
- src/terrama2/collector/DataProcessor.hpp
- src/terrama2/collector/DataSetTimer.cpp
- src/terrama2/collector/DataSetTimer.hpp
- src/terrama2/collector/Factory.cpp
- src/terrama2/collector/Factory.hpp
- src/terrama2/collector/Parser.hpp
- src/terrama2/collector/ParserOGR.cpp
- src/terrama2/collector/ParserOGR.hpp
- src/unittest/collector/TsCollectorFile.cpp
- src/unittest/collector/TsCollectorService.cpp
- src/unittest/collector/TsDataFilter.cpp
- src/unittest/collector/TsDataSetTimer.cpp
- src/unittest/collector/TsIntegration.cpp
- src/unittest/collector/TsParserOGR.cpp
- src/unittest/collector/TsStoragerPostGis.cpp
collector instantiate Parser, Storager and Filter and calls each of them.
DataProcessor not in use.
removing "#include *.moc" from Test files
> Changes from last meeting

- src/terrama2/collector/ParserOGR.cpp
- src/terrama2/collector/ParserOGR.hpp
Dataset modified without primary key - ParserOGR.
> Dataset modified without primary key - ParserOGR

- src/terrama2/collector/ParserOGR.cpp
- src/terrama2/collector/ParserOGR.hpp
Adjustment in collector ParserOGR
> Adjustment in collector ParserOGR

- src/terrama2/gui/config/ConfigAppWeatherGrid.cpp
- src/terrama2/gui/config/ConfigAppWeatherOccurrence.cpp
- src/terrama2/gui/config/ConfigAppWeatherPcd.cpp
- src/terrama2/gui/config/ConfigAppWeatherServer.cpp
- src/terrama2/gui/config/ConfigAppWeatherServer.hpp
- src/terrama2/gui/config/ConfigAppWeatherTab.cpp
- src/terrama2/gui/config/FilterDialog.cpp
- src/terrama2/gui/config/ui/ConfigAppForm.ui
> Adding data frequency fields, such second, and minute;
> Fixing datasetitem kind combobox index;
> code review: adding second,minute fields in each one dataset tab

- src/terrama2/collector/ParserOGR.cpp
- src/terrama2/collector/ParserOGR.hpp
- src/terrama2/collector/ParserPcdInpe.cpp
- src/terrama2/collector/ParserPcdInpe.hpp
- src/terrama2/collector/ParserPcdToa5.cpp
- src/terrama2/collector/ParserPcdToa5.hpp
- Create function to handle date and time field timestamp format to PCD INPE and TOA5.
> Adding Parser PCD INPE and TOA5

- src/terrama2/collector/CollectorService.cpp
- src/terrama2/collector/CollectorService.hpp
- src/terrama2/collector/DataFilter.cpp
- src/terrama2/collector/Factory.cpp
- src/terrama2/collector/Parser.hpp
- src/terrama2/collector/ParserOGR.cpp
- src/terrama2/collector/ParserOGR.hpp
- src/terrama2/collector/Storager.hpp
- src/terrama2/collector/StoragerPostgis.cpp
- src/terrama2/collector/StoragerPostgis.hpp
- src/terrama2/ws/collector/appserver/main.cpp
better thread management,
improving storager architecture,
optimizing ParserOGR,
Factory creates a postgis storager when no storageMetadata is created,
DataFilter is temporarily doing nothing in filter dataset
> CollectorService improvements

- build/cmake/CMakeLists.txt
- build/cmake/terrama2_gui_config/CMakeLists.txt
- src/terrama2/gui/config/ConfigApp.hpp
- src/terrama2/gui/config/ConfigAppWeatherGrid.cpp
- src/terrama2/gui/config/ConfigAppWeatherServer.cpp
- src/terrama2/gui/config/ConfigAppWeatherServer.hpp
- src/terrama2/gui/config/ConfigAppWeatherTab.cpp
- src/terrama2/gui/config/ConfigAppWeatherTab.hpp
- src/terrama2/gui/config/ui/ConfigAppForm.ui
> adding dataprovider ping with libcurl;
> adding cmake for libcurl;
> adding documentation in methods at config module
> adding dataprovider ping with libcurl

- src/terrama2/ws/collector/core/Utils.hpp
- src/terrama2/ws/collector/core/WebServiceDataTypes.hpp
- src/unittest/ws/collector/integration/TsClient.cpp
- src/unittest/ws/collector/integration/main.cpp
- src/unittest/ws/collector/server/TsWebService.cpp
To fix tests, must use real values in the tests
> Added path in the dataSetItem (Tests not working)

- src/terrama2/collector/CollectorService.cpp
- src/terrama2/gui/admin/ServicesDialog.cpp
Fix in CollectorService stop conditions,
Fix Admin interface start appserver parameters
> Fixing deadlock

- build/cmake/CMakeLists.txt
- build/cmake/terrama2_mod_collector/CMakeLists.txt
- src/terrama2/collector/CollectorService.cpp
- src/terrama2/collector/DataFilter.cpp
- src/terrama2/collector/DataFilter.hpp
- src/terrama2/collector/DataRetriever.cpp
- src/terrama2/collector/DataRetriever.hpp
- src/terrama2/collector/DataRetrieverFTP.cpp
- src/terrama2/collector/DataRetrieverFTP.hpp
Adding collector DataFilter;
Adding regex in CMackelists;
Adding parameter datasetitem in method collector::DataRetrieved.
> Adding Collector DataFilter and checked modifications CMakelist

- share/terrama2/sql/terrama2-data-model-pg.sql
- src/terrama2/collector/CollectorService.cpp
- src/terrama2/collector/DataFilter.cpp
- src/terrama2/collector/DataFilter.hpp
- src/terrama2/collector/DataRetriever.cpp
- src/terrama2/collector/DataRetriever.hpp
- src/terrama2/collector/DataRetrieverFTP.cpp
- src/terrama2/collector/DataRetrieverFTP.hpp
- src/terrama2/collector/Exception.hpp
- src/terrama2/collector/Log.cpp
- src/terrama2/collector/Log.hpp
- src/terrama2/collector/Storager.hpp
- src/terrama2/collector/StoragerPostgis.cpp
- src/terrama2/collector/StoragerPostgis.hpp
Changes in data model! Need to update your DB!
> Log imported data

- src/terrama2/collector/DataFilter.cpp
- src/terrama2/collector/DataFilter.hpp
- src/terrama2/collector/DataRetriever.cpp
- src/terrama2/collector/DataRetriever.hpp
- src/terrama2/collector/DataRetrieverFTP.cpp
- src/terrama2/collector/DataRetrieverFTP.hpp
- src/terrama2/collector/ParserFirePoint.cpp
- src/terrama2/collector/ParserFirePoint.hpp
- src/terrama2/collector/ParserOGR.cpp
- src/terrama2/collector/ParserOGR.hpp
- src/terrama2/collector/ParserPcdInpe.cpp
- src/terrama2/collector/ParserPcdInpe.hpp
- src/terrama2/collector/ParserPcdToa5.cpp
- src/terrama2/collector/ParserPcdToa5.hpp
- Creating Filters for burning data, INPE PCD, PCD TOA5 and ETA15km grid using regex in DataFilter class;
- Testing with FTP server using DataFilter class.
- Add comments in classes;
- Regex Library Addition in Cmakelist;
- Ticket # 205 Save the file names in memory.
-  Ticket # 206  Remove files downloaded after stored.
> Adjustment DataRetrieverFTP - adding function write_vector save the file names in memory.

- share/terrama2/sql/terrama2-data-model-pg.sql
- share/terrama2/sql/terrama2-data-model-pg_oneline.sql
- src/integrationtest/ws/collector/TsClient.cpp
- src/integrationtest/ws/collector/main.cpp
- src/terrama2/collector/DataFilter.cpp
- src/terrama2/core/DataSet.cpp
- src/terrama2/core/DataSet.hpp
- src/terrama2/core/DataSetDAO.cpp
- src/terrama2/core/Filter.cpp
- src/terrama2/core/Filter.hpp
- src/terrama2/core/FilterDAO.cpp
- src/terrama2/core/Intersection.cpp
- src/terrama2/core/Intersection.hpp
- src/terrama2/core/IntersectionDAO.cpp
- src/terrama2/core/IntersectionDAO.hpp
- src/terrama2/gui/config/ConfigAppWeatherOccurrence.cpp
- src/terrama2/gui/config/ConfigAppWeatherOccurrence.hpp
- src/terrama2/gui/config/ConfigAppWeatherTab.cpp
- src/terrama2/gui/config/IntersectionDialog.cpp
- src/terrama2/gui/config/IntersectionDialog.hpp
- src/terrama2/gui/config/ui/IntersectionDialogForm.ui
- src/terrama2/gui/core/ConfigManager.cpp
- src/terrama2/ws/collector/client/Client.cpp
- src/terrama2/ws/collector/core/Utils.hpp
- src/terrama2/ws/collector/core/WebServiceDataTypes.hpp
- src/terrama2/ws/collector/server/WebService.cpp
- src/unittest/core/TsDataManager.cpp
- src/unittest/core/Utils.cpp
- src/unittest/ws/collector/client/TsClient.cpp
- src/unittest/ws/collector/core/TsCore.cpp
Replacing DateTime for TimeInstantTZ in filter class
> Adding Intersection to the dataset

- src/terrama2/collector/CollectorService.cpp
- src/terrama2/core/DataSetItemDAO.cpp
- src/terrama2/core/FilterDAO.cpp
- src/terrama2/core/FilterDAO.hpp
- src/terrama2/gui/config/ConfigAppWeatherGrid.cpp
- src/terrama2/gui/config/ConfigAppWeatherOccurrence.cpp
- src/terrama2/gui/config/ConfigAppWeatherPcd.cpp
- src/terrama2/gui/config/ConfigAppWeatherTab.cpp
- src/terrama2/gui/config/FilterDialog.cpp
- src/terrama2/gui/config/FilterDialog.hpp
- src/terrama2/gui/config/ui/ConfigAppForm.ui
- src/terrama2/gui/config/ui/FilterDialogForm.ui
Filter for dates is not working, TerraLib has a problem being fixed.
> Timezone fixes

- src/terrama2/collector/Utils.cpp
- src/terrama2/collector/Utils.hpp
- src/terrama2/gui/config/FilterDialog.cpp
> updating helper in collector
> code review: filter dialog
> updating helper in collector

- src/terrama2/collector/CollectorService.cpp
- src/terrama2/collector/DataRetrieverFTP.cpp
- src/terrama2/collector/DataRetrieverFTP.hpp
- src/terrama2/collector/Exception.hpp
- src/terrama2/collector/ParserAscGrid.cpp
- src/terrama2/collector/ParserAscGrid.hpp
- src/terrama2/collector/ParserGDAL.cpp
- src/terrama2/collector/ParserGDAL.hpp
- src/terrama2/collector/ParserOGR.cpp
- src/terrama2/collector/ParserOGR.hpp
- src/terrama2/collector/ParserPcdInpe.hpp
- src/terrama2/collector/ParserPcdToa5.hpp
- src/terrama2/collector/ParserPostgis.hpp
- src/terrama2/collector/ParserTiff.cpp
- src/terrama2/collector/ParserTiff.hpp
- src/terrama2/collector/StoragerTiff.cpp
- src/terrama2/gui/core/Utils.cpp
- src/unittest/collector/TsParserAscGrid.cpp
- src/unittest/collector/TsParserAscGrid.hpp
- src/unittest/collector/TsParserOGR.cpp
- src/unittest/collector/TsParserTiff.cpp
- src/unittest/collector/TsParserTiff.hpp
- src/unittest/collector/main.cpp
log is commented while waits for fix
> Parser for tiff and asc-grid, fixes to the collecting process

- src/terrama2/collector/CollectorService.cpp
- src/terrama2/collector/DataFilter.cpp
- src/terrama2/collector/DataRetrieverFTP.cpp
- src/terrama2/collector/DataSetTimer.cpp
- src/terrama2/collector/Factory.cpp
- src/terrama2/collector/ParserFirePoint.cpp
- src/terrama2/collector/ParserGDAL.cpp
- src/terrama2/collector/ParserOGR.cpp
- src/terrama2/collector/ParserPcdInpe.cpp
- src/terrama2/collector/ParserPcdToa5.cpp
- src/terrama2/collector/ParserPostgis.cpp
- src/terrama2/collector/StoragerPostgis.cpp
- src/terrama2/collector/StoragerTiff.cpp
- src/terrama2/collector/Utils.hpp
collector log adjustments,
fixing fire points time
> collector log, fire point

- src/integrationtest/ws/collector/TsClient.cpp
- src/terrama2/collector/DataSetTimer.cpp
- src/terrama2/collector/DataSetTimer.hpp
- src/unittest/collector/TsDataSetTimer.cpp
- src/unittest/collector/TsDataSetTimer.hpp
- src/unittest/collector/main.cpp
> DataSetTimer with schedule

- src/terrama2/core/data-model/DataProvider.hpp
- src/terrama2/core/data-model/DataSeries.hpp
Data Model - DataProvider and DataSeries
> Data Model - DataProvider and DataSeries

- src/unittest/collector/main.cpp
Update the main Class Unittest.
> Update the main Class Unittest

- build/cmake/CMakeLists.txt
- build/cmake/modules/FindQuaZip.cmake
- build/cmake/terrama2_mod_collector/CMakeLists.txt
- install/install-3rdparty-linux-ubuntu-14.04.sh
- install/install-3rdparty-macosx-el-capitan.sh
- install/install-3rdparty-macosx-yosemite.sh
- src/terrama2/collector/Unpack.cpp
- src/unittest/collector/TsUnpack.cpp
- src/unittest/collector/main.cpp
Adding Quazip pack:
Update script install-3rdparty-linux-ubuntu-14.04.sh.
Update CMakelist.
Update CMakelist module Collector.
> Adding Quazip pack

- src/examples/core/AccessDcpToa5FromLocal.cpp
- src/terrama2/core/data-access/DataAccessor.cpp
- src/terrama2/core/data-access/DataAccessor.hpp
- src/terrama2/impl/DataAccessorDcpToa5.cpp
- src/terrama2/impl/DataAccessorDcpToa5.hpp
-  Addition "method make" of  in Class Data Retrieve FTP;
- Ticket # 350 - Use function to determine if the string is a number;
- Ticket # 351 - The GetFolder function should be specific Toa5, do not use the dataAccessor;
- Change of variable names. Ex timestampcolumn to timestampProperty.
> Adjustments in class toa5.

- webapp/core/DataManager.js
- webapp/core/FileRequest.js
- webapp/core/TcpManager.js
- webapp/core/data-model/AbstractData.js
- webapp/core/data-model/DataSeries.js
- webapp/core/data-model/DataSet.js
- webapp/core/data-series-semantics/Factory.js
- webapp/core/data-series-semantics/WildFire.js
- webapp/public/javascripts/angular/advanced.html
- webapp/public/javascripts/angular/data-provider/registration.js
- webapp/public/javascripts/angular/data-series/data-series.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/dataSeriesRegistration.js
- webapp/public/javascripts/angular/wizard.html
- webapp/views/configuration/dataset.html
- webapp/views/configuration/projects.html
- retrieving data set dcp position as wkt format;
- sending signal after provider and data series registration (prototype);
- fixing inherits call;
- adding alert box in data series registration, fixing error message data series;
> sending signal after data provider and data series registration

- install/install-3rdparty-linux-ubuntu-14.04.sh
- install/install-3rdparty-macosx-el-capitan.sh
- install/install-3rdparty-macosx-yosemite.sh
Ajustments in script install-3rdparty for linux and macOS:
- Adding install Quazip.
> Ajustments in script install-3rdparty for linux and macOS

- webapp/controllers/api/DataSeries.js
- webapp/core/DataManager.js
- webapp/core/data-series-semantics/WildFire.js
- webapp/public/javascripts/angular/analysis/registration.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/data-series/templates/storager.html
- webapp/public/javascripts/angular/wizard.html
- webapp/views/administration/user.html
- webapp/views/configuration/analysis.html
- webapp/views/configuration/dataset.html
- adding dataprovider output in storager
- adding mask in wil fires
- adding analysis message handler in template
> adding dataprovider output in storager

- webapp/controllers/api/Analysis.js
- webapp/controllers/api/DataSeries.js
- webapp/core/AbstractSemantics.js
- webapp/core/DataManager.js
- webapp/core/data-model/Analysis.js
- webapp/core/data-model/AnalysisDataSeries.js
- webapp/core/data-model/Collector.js
- webapp/core/data-series-semantics/WildFire.js
- webapp/locales/en.js
- webapp/public/javascripts/angular/analysis/registration.js
- webapp/public/javascripts/angular/data-series/data-series.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/generalData.html
- webapp/public/javascripts/angular/services.js
- webapp/routes/api/Analysis.js
- webapp/views/configuration/analysis.html
- webapp/views/configuration/dynamicDataSeries.html
- adding collector structure: sending it in tcp
- filtering dataseries with output and processing; 
- adding analysis validation (template)
> adding collector structure: sending via tcp

- webapp/controllers/api/DataSeries.js
- webapp/core/DataManager.js
- webapp/core/data-series-semantics/WildFire.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/views/configuration/dynamicDataSeries.html
- fixing dataseries collector: sending tcp;
- changing wild-fires to OCCURRENCE-wfp
> fixing dataseries collector: sending tcp

- webapp/controllers/api/DataSeries.js
- webapp/core/data-model/Collector.js
- webapp/public/javascripts/angular/advanced.html
- webapp/public/javascripts/angular/alert-box/directives.js
- webapp/public/javascripts/angular/alert-box/templates/message-box.html
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/wizard.html
- webapp/views/base/layout.html
- removing databases tab in adminstration
> fixing collector intersection

- webapp/core/DataManager.js
- webapp/public/javascripts/angular/analysis/registration.js
- webapp/public/javascripts/angular/data-series/templates/schedule.html
> fixing js: sending analysis and storager object

- webapp/controllers/api/Remote.js
- webapp/core/SSHDispatcher.js
- webapp/core/Utils.js
- webapp/public/javascripts/angular/table/templates/table.html
- webapp/public/stylesheets/terrama2.css
- webapp/views/administration/services.html
> fixing ssh start service
> adding utils for handling add signal message
> fixing ssh start service

- webapp/core/SSHDispatcher.js
- webapp/core/Utils.js
> adding utils for finding files in path
> ssh search for a private key in ~/.ssh (id_rsa/id_dsa/id_...)
> fixing ssh key

- webapp/controllers/administration/Service.js
- webapp/controllers/api/DataSeries.js
- webapp/controllers/api/Service.js
- webapp/core/DataManager.js
- webapp/core/data-model/AbstractData.js
- webapp/core/data-model/Log.js
- webapp/core/data-model/Service.js
- webapp/models/Log.js
- webapp/models/ServiceInstance.js
- webapp/views/administration/service.html
> fixing get service in dataseries
> adding log fields in terrama2 services page
> fixing get service in dataseries

- README
- README.md
- webapp/controllers/api/DataSeries.js
- webapp/controllers/api/Remote.js
- webapp/core/DataManager.js
- webapp/core/Service.js
- webapp/core/TcpManager.js
- webapp/core/Utils.js
- webapp/models/DataSet.js
- webapp/views/administration/service.html
> adding readme with build-status
> fixing stop service and loading dset format
> exception handling while parsing bytearray;
> fixing stop service

- src/terrama2/core/data-access/DataAccessor.cpp
- src/terrama2/core/network/TcpManager.cpp
- src/terrama2/core/network/TcpManager.hpp
- src/terrama2/core/utility/JSonUtils.cpp
- src/terrama2/core/utility/Logger.hpp
- src/terrama2/core/utility/ProcessLogger.cpp
- src/terrama2/core/utility/ServiceManager.cpp
- src/terrama2/core/utility/Timer.cpp
- src/terrama2/impl/DataAccessorFile.cpp
- src/terrama2/impl/DataStoragerPostGis.cpp
- src/terrama2/services/analysis/core/DataManager.hpp
- src/terrama2/services/collector/appserver/main.cpp
- src/terrama2/services/collector/core/JSonUtils.cpp
better error messages,
better handling for null data timestamps
fix on log database parse
fix on date filter for dataset
> Collector fix and debug

- src/terrama2/core/semantics.json
- src/terrama2/core/utility/FilterUtils.cpp
- src/terrama2/core/utility/Utils.cpp
- src/terrama2/core/utility/Utils.hpp
- src/terrama2/impl/DataAccessorFile.cpp
- src/terrama2/impl/DataAccessorFile.hpp
- src/terrama2/impl/DataAccessorOccurrenceWfp.hpp
- src/terrama2/services/collector/appserver/main.cpp
- src/terrama2/services/collector/core/JSonUtils.cpp
- webapp/locales/en.js
fix TimeInstantTZ comparison,
fix WFP data timestamp validation
> Semantics file and fixes

- webapp/controllers/api/Analysis.js
- webapp/controllers/api/DataProvider.js
- webapp/controllers/api/DataSeriesSemantics.js
- webapp/controllers/configuration/DataProvider.js
- webapp/controllers/configuration/DynamicDataSeries.js
- webapp/core/DataManager.js
- webapp/core/Enums.js
- webapp/core/FtpRequest.js
- webapp/core/data-model/Analysis.js
- webapp/models/Analysis.js
- webapp/models/AnalysisDataSeries.js
- webapp/models/DataProviderType.js
- webapp/models/DataSeriesSemantics.js
- webapp/package.json
- webapp/public/javascripts/angular/analysis/registration.js
- webapp/public/javascripts/angular/data-provider/registration.js
- webapp/public/javascripts/angular/table/templates/table.html
- webapp/views/configuration/analyses.html
- webapp/views/configuration/analysis.html
> adding script field in Analysis model object
> fixing data provider ftp
> fixing analysis listing
> fixing analysis object and services status icon color
**Note**
* Go to webapp directory and run npm install
* Models has been updated. In order to working correctly, drop and create terrama2 schema.
> fixing analysis: adding script id, removing extra analysis semantics

- webapp/core/DataManager.js
- webapp/core/Enums.js
- webapp/core/data-model/DataSetMonitored.js
- webapp/locales/en.js
- webapp/models/DataSet.js
- webapp/public/javascripts/angular/analysis/registration.js
- webapp/views/configuration/analysis.html
* fixing enums, analysis registration, template review
* fixing analysis and model DataSet orm linking
> fixing enums, analysis registration, template review

- webapp/core/Enums.js
- webapp/core/Exceptions.js
- webapp/core/SSHDispatcher.js
- webapp/core/Utils.js
- webapp/views/administration/service.html
updating ssh command, adding service type exception and enum
> updating ssh command: service 

- src/examples/analysis/Buffer.cpp
- src/examples/analysis/ListenToTcpAndRunAnalysis.cpp
- src/examples/analysis/OperatorDCP.cpp
- src/examples/analysis/OperatorHistoryDCP.cpp
- src/examples/analysis/OperatorOccurrence.cpp
- src/examples/analysis/OperatorOccurrenceAggregation.cpp
- src/terrama2/services/analysis/core/Analysis.hpp
- src/terrama2/services/analysis/core/AnalysisExecutor.cpp
- src/terrama2/services/analysis/core/BufferMemory.cpp
- src/terrama2/services/analysis/core/Context.cpp
- src/terrama2/services/analysis/core/JSonUtils.cpp
- src/terrama2/services/analysis/core/PythonInterpreter.cpp
- src/terrama2/services/analysis/core/PythonInterpreter.hpp
- src/terrama2/services/analysis/core/Service.cpp
- src/terrama2/services/analysis/core/Utils.cpp
- src/terrama2/services/analysis/core/dcp/Operator.cpp
- src/terrama2/services/analysis/core/dcp/history/Operator.cpp
- src/terrama2/services/analysis/core/occurrence/Operator.cpp
- src/terrama2/services/analysis/core/occurrence/aggregation/Operator.cpp
Refacoring enum types in analysis module and validating service instance id before running the analysis
> Refacoring enum types in analysis module

- webapp/controllers/api/DataSeriesSemantics.js
- webapp/core/AbstractSemantics.js
- webapp/core/Utils.js
- webapp/core/data-model/Analysis.js
- webapp/core/data-series-semantics/Dcp.js
- webapp/core/data-series-semantics/DcpInpe.js
- webapp/core/data-series-semantics/DcpPostgis.js
- webapp/core/data-series-semantics/DcpToa5.js
- webapp/core/data-series-semantics/Factory.js
- webapp/core/data-series-semantics/FileStaticDataOgr.js
- webapp/core/data-series-semantics/GridGeoTiff.js
- webapp/core/data-series-semantics/Occurrence.js
- webapp/core/data-series-semantics/OccurrencePostgis.js
- webapp/core/data-series-semantics/PostgisStaticDataOgr.js
- webapp/core/data-series-semantics/WildFire.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/views/base/404.html
* updating dataseries semantics classes
* service id in analysis object
* fixing 404 template
> updating dataseries semantics classes

- src/terrama2/core/utility/TimeUtils.cpp
- src/terrama2/core/utility/TimeUtils.hpp
- src/terrama2/services/analysis/core/BufferMemory.cpp
- src/terrama2/services/analysis/core/Context.cpp
Using meter as default unit for buffer
> Using hour as default unit for analysis date filter

- BUILD-INSTRUCTIONS
- DEPENDENCIES
- README.md
- src/examples/collector/CollectorServiceFromFileToPostGis.cpp
- src/examples/collector/ListenToTcpAndCollect.cpp
- src/examples/core/AccessAndFilterOccurrenceFromPostGis.cpp
- src/examples/core/AccessAndFilterOccurrenceMvfFromLocal.cpp
- src/examples/core/AccessAndStoreDcpInpeFromLocal.cpp
- src/examples/core/AccessAndStoreGridGeoTifFromLocal.cpp
- src/examples/core/AccessDcpInpeFromLocal.cpp
- src/examples/core/AccessDcpToa5FromLocal.cpp
- src/examples/core/AccessGridGeoTifFromLocal.cpp
- src/examples/core/AccessLastDcpInpeFromLocal.cpp
- src/examples/core/AccessLastOccurrenceFromPostGis.cpp
- src/examples/core/AccessOccurrenceMvfFromLocal.cpp
- src/examples/core/ListenToTcp.cpp
- src/terrama2/core/data-access/DataAccessor.cpp
- src/terrama2/core/data-access/DataAccessor.hpp
- src/terrama2/core/network/TcpManager.cpp
- src/terrama2/core/network/TcpManager.hpp
- src/terrama2/impl/DataAccessorDcpToa5.cpp
- src/terrama2/impl/DataAccessorDcpToa5.hpp
- src/terrama2/impl/DataAccessorFile.cpp
- src/terrama2/impl/DataAccessorFile.hpp
- src/terrama2/impl/DataAccessorOccurrenceWfp.cpp
- src/terrama2/impl/DataAccessorOccurrenceWfp.hpp
> fixing examples

- src/terrama2/services/analysis/Typedef.hpp
- src/terrama2/services/analysis/core/Analysis.hpp
- src/terrama2/services/analysis/core/AnalysisExecutor.cpp
- src/terrama2/services/analysis/core/Context.cpp
- src/terrama2/services/analysis/core/Context.hpp
- src/terrama2/services/analysis/core/OperatorCache.hpp
- src/terrama2/services/analysis/core/PythonInterpreter.cpp
- src/terrama2/services/analysis/core/PythonInterpreter.hpp
- src/terrama2/services/analysis/core/dcp/Operator.cpp
Adding exception to functions not implemented yet
> Creating typedef for analysis hashcode

- webapp/controllers/api/Analysis.js
- webapp/controllers/configuration/DynamicDataSeries.js
- webapp/controllers/configuration/StaticDataSeries.js
- webapp/core/DataManager.js
- webapp/core/Utils.js
- webapp/core/data-model/Analysis.js
- webapp/core/data-model/Collector.js
- webapp/core/data-series-semantics/DcpInpe.js
- webapp/core/data-series-semantics/DcpToa5.js
- webapp/public/javascripts/angular/advanced.html
- webapp/public/javascripts/angular/analysis/registration.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/data-series/schedule.js
- webapp/public/javascripts/angular/data-series/templates/schedule.html
- webapp/public/javascripts/angular/data-series/templates/storager.html
- webapp/public/javascripts/angular/dcpTable.html
- webapp/public/javascripts/angular/filter.html
- webapp/public/javascripts/angular/generalData.html
- webapp/public/javascripts/angular/wizard.html
- webapp/views/configuration/analysis.html
- webapp/views/configuration/dataset.html
- webapp/views/configuration/dynamicDataSeries.html
- webapp/views/configuration/staticData.html
* adding schedule in analysis, listing dataseries (occurrence);
* adding schedule in analysis
> fixing analysis web json

- webapp/controllers/configuration/Analysis.js
- webapp/core/DataManager.js
- webapp/core/data-model/AnalysisDataSeries.js
- webapp/models/Filter.js
- webapp/public/javascripts/angular/analysis/registration.js
- webapp/public/javascripts/angular/app.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/routes/configuration/Analysis.js
- webapp/views/configuration/analyses.html
- webapp/views/configuration/analysis.html
- webapp/views/configuration/status.html
* fixing filter timestamp, removing status object list;
* adding mock for fill analysis in gui web.
> fixing filter timestamp, removing status object list

- webapp/core/DataManager.js
- webapp/public/javascripts/angular/analysis/registration.js
- webapp/views/configuration/dynamicDataSeries.html
* analysis listing with values (fields disabled )
> adding filter in script: add_value

- webapp/controllers/api/Analysis.js
- webapp/controllers/api/DataSeries.js
- webapp/controllers/configuration/Analysis.js
- webapp/core/DataManager.js
- webapp/locales/en.js
- webapp/public/javascripts/angular/alert-box/directives.js
- webapp/public/javascripts/angular/alert-box/templates/modal.html
- webapp/public/javascripts/angular/analysis/registration.js
- webapp/public/javascripts/angular/services.js
- webapp/routes/configuration/Analysis.js
- webapp/sockets/DbConnectionChecker.js
- webapp/views/administration/service.html
- webapp/views/configuration/analyses.html
- webapp/views/configuration/analysis.html
* adding log check connection in service registration;
* removing schedule while deleting analysis;
* removing schedule while deleting collector;
* template review: adding new modal directive and socket directive with angular;
> adding log check connection in service registration

- src/unittest/core/MockDataRetriever.hpp
- src/unittest/core/TsDataAccessorDcpInpe.cpp
- src/unittest/core/TsDataAccessorDcpInpe.hpp
- src/unittest/core/main.cpp
Adjustment main unittest;
Adding TsDataAccessorDcpInpe.
> Adding unittest TsDataAccessorDcpInpe

- build/cmake/terrama2_unittest_analysis/CMakeLists.txt
- build/cmake/terrama2_unittest_collector/CMakeLists.txt
- src/terrama2/core/data-access/DataAccessor.hpp
adding system flag to 3party libs
> adding virtual to assignment operator of DataAccessor,

- build/cmake/CMakeLists.txt
- src/examples/analysis/Buffer.cpp
- src/examples/analysis/ListenToTcpAndRunAnalysis.cpp
- src/examples/analysis/OperatorDCP.cpp
- src/examples/analysis/OperatorHistoryDCP.cpp
- src/examples/analysis/OperatorOccurrence.cpp
- src/examples/analysis/OperatorOccurrenceAggregation.cpp
- src/examples/collector/ListenToTcpAndCollect.cpp
- src/examples/core/ListenToTcp.cpp
- src/examples/core/ProcessLogger.cpp
- src/terrama2/core/network/TcpManager.cpp
- src/terrama2/core/network/TcpManager.hpp
- src/terrama2/core/utility/ProcessLogger.cpp
- src/terrama2/core/utility/ProcessLogger.hpp
- src/terrama2/core/utility/Service.hpp
- src/terrama2/services/analysis/core/AnalysisLogger.cpp
- src/terrama2/services/analysis/core/AnalysisLogger.hpp
- src/terrama2/services/analysis/core/Service.cpp
- src/terrama2/services/analysis/core/Service.hpp
- src/terrama2/services/appserver/main.cpp
- src/terrama2/services/collector/core/CollectorLogger.cpp
- src/terrama2/services/collector/core/CollectorLogger.hpp
- src/terrama2/services/collector/core/Service.cpp
- src/terrama2/services/collector/core/Service.hpp
- src/unittest/core/TestLogger.hpp
fix on missing terrama2_service
> Log SIGNAL response

- src/terrama2/core/data-access/DataAccessor.cpp
- src/terrama2/core/semantics.json
- src/terrama2/core/utility/Utils.cpp
- src/terrama2/core/utility/Utils.hpp
- src/terrama2/impl/DataAccessorFile.cpp
- src/terrama2/impl/DataAccessorFile.hpp
- src/terrama2/impl/DataAccessorGeoTiff.cpp
- src/terrama2/impl/DataAccessorOccurrenceWfp.cpp
- src/terrama2/impl/DataStoragerTiff.cpp
- src/terrama2/impl/DataStoragerTiff.hpp
fix type conversions and comparisons of signed and unsigned
> Fix to access geotiff example

- src/unittest/core/TsDataAccessorDcpInpe.cpp
- src/unittest/core/TsDataAccessorDcpToa5.cpp
- src/unittest/core/TsDataAccessorGeoTiff.cpp
- src/unittest/core/TsDataAccessorOccurrenceWfp.cpp
- src/unittest/core/TsDataRetrieverFTP.cpp
Review error message in unittest:
- TsDataRetrieverFTP.hpp;
- TsDataAccessorDcpInpe.hpp;
- TsDataAccessorDcpToa5.hpp;
- TsDataAccessorGeoTiff.hpp;
- TsDataAccessorOccurrenceWfp.hpp.
> Review error message in unittest.

- webapp/bin/www
- webapp/controllers/api/Service.js
- webapp/core/DataManager.js
- webapp/core/Enums.js
- webapp/core/PortScanner.js
- webapp/core/SSHDispatcher.js
- webapp/core/Service.js
- webapp/core/TcpManager.js
- webapp/public/javascripts/angular/services.js
- webapp/public/javascripts/angular/services/registration.js
- webapp/public/javascripts/angular/services/service.js
- webapp/routes/api/Service.js
- webapp/sockets/ServicePortChecker.js
- webapp/sockets/TcpSocket.js
- webapp/views/administration/service.html
**Notes**
In order to use SSH, you must install Screen command. 
Ubuntu 14.04 - ```sudo apt-get install screen```
Mac OSX (not tested) - https://gist.github.com/bigeasy/2327150
* suggesting port number in service registration;
* updating ssh to use screen command
* updating service
> adding port suggestion and ssh screen command

- webapp/controllers/api/Analysis.js
- webapp/controllers/api/DataSeries.js
- webapp/controllers/api/Service.js
- webapp/core/DataManager.js
- webapp/core/Service.js
- webapp/core/TcpManager.js
- webapp/core/Utils.js
- webapp/package.json
* fixing web dependencies (package.json)
* fixing nodejs buffer
> fixing nodejs buffer

- src/terrama2/core/utility/Unpack.cpp
- src/terrama2/core/utility/Unpack.hpp
Ticket #544 Remove using fprintf, Terrama log macros should be used.
> Remove using fprintf, TerraMA log macros should be used.

- src/examples/analysis/GridHistory.cpp
- src/examples/analysis/OperatorSampleGrid.cpp
- src/terrama2/services/analysis/core/Analysis.hpp
- src/terrama2/services/analysis/core/JSonUtils.cpp
- src/terrama2/services/analysis/core/Shared.hpp
- src/terrama2/services/analysis/core/Utils.cpp
- src/terrama2/services/analysis/core/dcp/influence/PythonOperator.hpp
Fix AnalysisOutputGrid enum values
Fix serialization of AnalysisOutputGrid
> Renaming OutputGrid class

- webapp/core/data-model/AnalysisOutputGrid.js
> Code review: renaming analysis output grid json key

- src/terrama2/services/analysis/core/AnalysisExecutor.cpp
- src/terrama2/services/analysis/core/PythonBindingMonitoredObject.cpp
- src/terrama2/services/analysis/core/PythonBindingMonitoredObject.hpp
- src/terrama2/services/analysis/core/dcp/influence/PythonOperator.hpp
Changing analysis result table to use unique key
Making buffer optional for influence by rule
> Refactoring registration of functions for monitored object analysis

- src/terrama2/services/analysis/core/AnalysisExecutor.cpp
- src/terrama2/services/analysis/core/grid/Operator.cpp
fix monitored object output table name,
fix grid coordinate inside interest area bug
> analysis review,

- webapp/controllers/administration/User.js
- webapp/controllers/api/DataProvider.js
- webapp/controllers/api/User.js
- webapp/controllers/configuration/Project.js
- webapp/core/DataManager.js
- webapp/core/Exceptions.js
- webapp/core/data-model/AnalysisOutputGrid.js
- webapp/locales/en.js
- webapp/public/javascripts/angular/analysis/registration.js
- webapp/public/javascripts/angular/services.js
- webapp/public/javascripts/angular/users/app.js
- webapp/public/javascripts/angular/users/controllers.js
- webapp/routes/Profile.js
- webapp/routes/api/User.js
- webapp/views/base/layout.html
- webapp/views/profile.html
> Code fixes and adding profile feature

- webapp/controllers/configuration/DynamicDataSeries.js
- webapp/core/DataManager.js
> Code fixes: Analysis

- build/cmake/terrama2_unittest_view/CMakeLists.txt
- src/terrama2/core/data-access/DataAccessorDcp.hpp
- src/terrama2/core/data-access/DataAccessorGrid.hpp
- src/terrama2/core/data-access/DataAccessorOccurrence.hpp
- src/terrama2/services/analysis/core/AnalysisExecutor.cpp
- src/terrama2/services/analysis/core/JSonUtils.cpp
- src/terrama2/services/analysis/core/PythonBindingGrid.cpp
- src/terrama2/services/analysis/core/PythonBindingMonitoredObject.cpp
- src/terrama2/services/analysis/core/Utils.cpp
- src/terrama2/services/analysis/core/grid/Operator.cpp
- src/terrama2/services/collector/core/IntersectionOperation.cpp
fix coordinate in grid,
fix raster resample
remove warnings
> Fix to analysis

- webapp/controllers/api/DataSeries.js
- webapp/controllers/configuration/DynamicDataSeries.js
- webapp/core/DataManager.js
- webapp/core/Enums.js
- webapp/core/UriBuilder.js
- webapp/core/Utils.js
- webapp/core/data-model/Analysis.js
- webapp/core/data-model/AnalysisOutputGrid.js
- webapp/core/data-model/Collector.js
- webapp/core/data-model/DataProvider.js
- webapp/core/data-model/DataSetDcp.js
- webapp/core/data-model/Schedule.js
- webapp/core/filters/CollectorFilter.js
- webapp/models/Schedule.js
- webapp/public/javascripts/angular/analysis/registration.js
- webapp/public/javascripts/angular/data-series/schedule.js
- webapp/public/javascripts/angular/data-series/templates/schedule.html
- webapp/public/javascripts/angular/geo/directives.js
- webapp/views/configuration/analysis.html
> Code review: adding frequency_start_time and analysis features

- webapp/core/DataManager.js
- webapp/core/data-model/Schedule.js
- webapp/core/data-model/index.js
- webapp/core/filters/CollectorFilter.js
- webapp/public/javascripts/angular/analysis/registration.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/filter.html
- webapp/public/javascripts/angular/geo/app.js
- webapp/public/javascripts/angular/geo/directives.js
- webapp/views/configuration/analysis.html
- webapp/views/configuration/dataset.html
> changing wkt to ewkt

- share/terrama2/semantics.json
- webapp/controllers/api/Analysis.js
- webapp/controllers/configuration/Analysis.js
- webapp/core/DataManager.js
- webapp/core/Enums.js
- webapp/core/Utils.js
- webapp/core/data-model/Analysis.js
- webapp/core/data-model/Collector.js
- webapp/core/data-model/Schedule.js
- webapp/core/data-series-semantics/Factory.js
- webapp/core/data-series-semantics/Grads.js
- webapp/core/facade/Analysis.js
- webapp/models/DataSeriesSemantics.js
- webapp/public/javascripts/angular/analysis/registration.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/data-series/schedule.js
- webapp/public/javascripts/angular/generalData.html
- webapp/views/configuration/analyses.html
- webapp/views/configuration/analysis.html
- webapp/views/configuration/dynamicDataSeries.html
> Adding grads registration and fixing dynamic data series list

- webapp/controllers/api/DataSeries.js
- webapp/core/AbstractRequest.js
- webapp/core/DataManager.js
- webapp/core/Utils.js
- webapp/models/Intersection.js
- webapp/public/javascripts/angular/app.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/data-series/templates/intersection.html
- webapp/public/javascripts/angular/filter.html
- webapp/public/stylesheets/terrama2.css
- webapp/views/configuration/dataset.html
**Note** Intersection model updated. Please remove _Not Null_ constraint ```attribute``` of ```intersection``` table if there a database active.
> Fixing intersection and filter update

- src/terrama2/core/data-access/DataAccessor.cpp
- src/terrama2/core/utility/CurlPtr.cpp
- src/terrama2/core/utility/Utils.cpp
- src/terrama2/core/utility/Utils.hpp
- src/terrama2/impl/DataAccessorGrADS.cpp
- src/terrama2/impl/DataRetrieverFTP.cpp
- src/terrama2/impl/DataStoragerPostGis.cpp
- src/terrama2/impl/DataStoragerPostGis.hpp
- src/terrama2/impl/DataStoragerTiff.cpp
- src/terrama2/services/analysis/core/Service.cpp
- src/terrama2/services/collector/core/IntersectionOperation.cpp
- src/terrama2/services/collector/core/Service.cpp
[x] Fixed bug where column names were compared wrongly
[x] Logging exceptions messages in collection
[x] Fix reading grads file extension
[x] Fix curl bug
[x] Reading GraDS file with a vrt (no flip)
= Restricting number of threads and bands in grads files for Alpha3 =
> fix bug where column names were compared wrongly

- src/terrama2/services/analysis/core/JSonUtils.cpp
removing dependency of reprocessing_historical_data while in development
> using default timefacet,

- webapp/sockets/ImportExport.js
It fixes filter date importer.
> adding filter date on import: ImportExport.js

- src/terrama2/services/analysis/core/grid/zonal/history/prec/Operator.cpp
- src/terrama2/services/analysis/core/grid/zonal/history/prec/Operator.hpp
> Point and Line Monitored objects

- webapp/locales/pt.js
- webapp/public/javascripts/angular/analysis/registration.js
- webapp/public/javascripts/angular/data-provider/registration.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/projects/app.js
- webapp/public/javascripts/angular/projects/controllers.js
- webapp/views/configuration/analysis.html
- webapp/views/configuration/project.html
[x] - Mostrar o message box de erro informando que existe campos invalidos [681](https://trac.dpi.inpe.br/terrama2/ticket/681)
> Box com messagem de erros nos formularios de configuracoes

- README.md
- webapp/app.js
- webapp/config/Database.js
- webapp/config/Passport.js
- webapp/controllers/api/DataSeriesSemantics.js
- webapp/core/TcpManager.js
- webapp/core/Utils.js
- webapp/locales/en.js
- webapp/public/javascripts/angular/app.js
- webapp/public/javascripts/angular/data-provider/registration.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/datetimepicker/templates/filterdatetimepicker.html
- webapp/public/javascripts/angular/filter.html
- webapp/public/javascripts/angular/wizard.html
- webapp/sockets/TcpSocket.js
> Web fixes: build health status and auto-socket connection

- build/cmake/terrama2_collector_core/CMakeLists.txt
- build/cmake/terrama2_core/CMakeLists.txt
- src/terrama2/core/utility/Utils.cpp
- src/terrama2/core/utility/Utils.hpp
- src/terrama2/services/analysis/core/dcp/Operator.cpp
- src/terrama2/services/collector/core/IntersectionOperation.cpp
would cause random crashed while finalizing
> removing dependency of terralib_mod_sa_core

- webapp/public/javascripts/angular/status/status.js
- webapp/public/javascripts/angular/table/table.js
- webapp/views/configuration/status.html
[x] - Improve status interface - created a modal to show all messages of the status [654](https://trac.dpi.inpe.br/terrama2/ticket/654)
> Improve status interface

- src/examples/analysis/ReprocessingHistoricalData.cpp
- src/examples/collector/CollectorServiceFromFileToPostGis.cpp
- src/terrama2/core/network/TcpManager.cpp
- src/terrama2/core/utility/ServiceManager.cpp
- src/terrama2/services/alert/core/RunAlert.cpp
- src/terrama2/services/analysis/core/Service.cpp
- src/terrama2/services/analysis/core/utility/Utils.cpp
- src/terrama2/services/collector/core/Service.cpp
Return status when service not loaded: [#691](https://trac.dpi.inpe.br/terrama2/ticket/691)
minor fixes
> Return status when service not loaded

- build/cmake/terrama2_view_core/CMakeLists.txt
- src/examples/view/Geoserver.cpp
- src/examples/view/Utils.hpp
- src/terrama2/services/view/core/JSonUtils.cpp
- src/terrama2/services/view/data-access/Exception.hpp
- src/terrama2/services/view/data-access/Geoserver.cpp
- src/terrama2/services/view/data-access/Geoserver.hpp
- src/unittest/view/Utils.hpp
Service communication with GeoServer, allows register and delete vector, raster and style in GeoServer
> View Service

- webapp/controllers/configuration/Analysis.js
- webapp/controllers/configuration/DynamicDataSeries.js
- webapp/controllers/configuration/Status.js
- webapp/core/DataManager.js
- webapp/core/Enums.js
- webapp/core/Utils.js
- webapp/core/data-series-semantics/Grads.js
- webapp/core/data-series-semantics/GridGeoTiff.js
- webapp/core/facade/Analysis.js
- webapp/locales/en.js
- webapp/locales/pt.js
- webapp/public/javascripts/angular/analysis/registration.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/routes/configuration/Analysis.js
- webapp/sockets/ImportExport.js
- webapp/sockets/TcpSocket.js
- webapp/views/base/layout.html
- webapp/views/configuration/analysis.html
- webapp/views/configuration/analysis_list.html
- webapp/views/configuration/dynamicDataSeries.html
> adding bytes offset in grads model and timezone

- webapp/core/Utils.js
Fixing variable context in ```webapp/core/Utils.js```
> Fixing variable context in Utils

- webapp/config/config.terrama2
- webmonitor/public/javascripts/app.js
- webmonitor/public/stylesheets/style.css
- webmonitor/views/index.html
- webmonitor/views/layout.html
> Base layout

- build/cmake/terrama2_view_core/CMakeLists.txt
- src/examples/view/Geoserver.cpp
- src/examples/view/Utils.hpp
- src/terrama2/services/view/core/JSonUtils.cpp
- src/terrama2/services/view/core/Service.hpp
- src/terrama2/services/view/core/View.hpp
- src/terrama2/services/view/data-access/Exception.hpp
- src/terrama2/services/view/data-access/Geoserver.cpp
- src/terrama2/services/view/data-access/Geoserver.hpp
- src/unittest/view/TsJsonUtils.cpp
Geoserver class to work with View Service
> View geoserver

- src/examples/analysis/OperatorHistoryDCP.cpp
- src/terrama2/services/analysis/core/AnalysisExecutor.cpp
- src/terrama2/services/analysis/core/BaseContext.cpp
- src/terrama2/services/analysis/core/BufferMemory.cpp
- src/terrama2/services/analysis/core/MonitoredObjectContext.cpp
- src/terrama2/services/analysis/core/MonitoredObjectContext.hpp
- src/terrama2/services/analysis/core/python/PythonInterpreter.cpp
Fix projection error from DCP operators
> Allow identifier column to be any data type for monitored object analysis

- webapp/controllers/api/DataProvider.js
- webapp/core/DataManager.js
- webapp/locales/en.json
- webapp/locales/en_US.json
- webapp/locales/pt_BR.json
- webapp/public/javascripts/angular/analysis/registration.js
- webapp/views/base/layout.html
- webapp/views/configuration/status.html
> Adding monitored_object_id in analysis output data series

- build/cmake/CMakeLists.txt
- src/examples/view/Geoserver.cpp
- src/terrama2/impl/DataAccessorPostGis.cpp
- src/terrama2/services/view/core/Service.cpp
- src/terrama2/services/view/core/Service.hpp
- src/terrama2/services/view/core/Typedef.hpp
- src/terrama2/services/view/core/data-access/Geoserver.cpp
- src/terrama2/services/view/core/data-access/Geoserver.hpp
- src/terrama2/services/view/core/serialization/Exception.hpp
View service create a table view in Geoserver;
Schedule validation;
Some fix in view service;
> Analysis result in Geoserver

- src/terrama2/services/view/core/data-access/Geoserver.cpp
> View service and postgis tables

- webapp/core/DataManager.js
- webapp/core/data-model/View.js
- webapp/public/javascripts/angular/views/controllers/view-register-update.js
- webapp/views/configuration/view.html
> Fixing view

- src/examples/analysis/GridHistory.cpp
- src/examples/collector/CollectorServiceFromFileToPostGis.cpp
- src/examples/collector/IntersectionGrid.cpp
- src/examples/collector/IntersectionStaticData.cpp
- src/examples/core/AccessAndFilterOccurrenceMvfFromLocal.cpp
- src/examples/core/AccessAndFilterOccurrenceMvfFromLocalFolder.cpp
- src/examples/core/AccessAndStoreGridGeoTifFromLocal.cpp
- src/examples/core/AccessAndStoreGridGrADSFromLocal.cpp
- src/examples/core/AccessOccurrenceMvfFromLocal.cpp
- src/examples/view/CreateGeoserverShapefile.cpp
- src/terrama2/core/utility/FilterUtils.cpp
- src/terrama2/impl/DataAccessorGrADS.cpp
- src/terrama2/impl/DataStoragerTiff.cpp
- src/terrama2/services/collector/core/Service.cpp
- src/unittest/core/TsUtility.cpp
Altering mask wildcards 
every wildcard will start with a %
and data wildcards are uppercase
> Altering mask wildcards 

- src/examples/analysis/Buffer.cpp
- src/examples/analysis/GridHistory.cpp
- src/examples/analysis/GridZonal.cpp
- src/examples/analysis/GridZonalHistoryRatio.cpp
- src/examples/analysis/OperatorDCP.cpp
- src/examples/analysis/OperatorHistoryDCP.cpp
- src/examples/analysis/OperatorHistoryIntervalDCP.cpp
- src/examples/analysis/OperatorOccurrence.cpp
- src/examples/analysis/OperatorOccurrenceAggregation.cpp
- src/examples/analysis/OperatorSampleGrid.cpp
- src/examples/analysis/ReprocessingHistoricalData.cpp
- src/terrama2/core/Shared.hpp
- src/terrama2/core/data-model/Process.hpp
- src/terrama2/core/utility/Service.cpp
- src/terrama2/core/utility/Service.hpp
- src/terrama2/services/analysis/core/Analysis.hpp
- src/terrama2/services/analysis/core/DataManager.cpp
- src/terrama2/services/analysis/core/DataManager.hpp
- src/terrama2/services/analysis/core/Service.cpp
- src/terrama2/services/analysis/core/Service.hpp
- src/terrama2/services/collector/core/Collector.hpp
- src/terrama2/services/collector/core/Service.cpp
- src/terrama2/services/collector/core/Service.hpp
- src/terrama2/services/view/core/Service.cpp
- src/terrama2/services/view/core/Service.hpp
- src/terrama2/services/view/core/View.hpp
unified add process to service,
unified add logger to service
> Unified scheduling process

- src/examples/analysis/OperatorOccurrence.cpp
- src/examples/analysis/OperatorOccurrenceAggregation.cpp
- src/terrama2/services/analysis/core/occurrence/Operator.cpp
- src/terrama2/services/analysis/core/occurrence/Operator.hpp
- src/terrama2/services/analysis/core/occurrence/aggregation/Operator.cpp
- src/terrama2/services/analysis/core/occurrence/aggregation/Operator.hpp
- src/terrama2/services/analysis/core/python/PythonBindingMonitoredObject.cpp
- src/terrama2/services/analysis/core/python/PythonBindingMonitoredObject.hpp
Fix aggregation_count operator
Occurrence operators parameters changed
> Changed occurrence operators parameters order

- src/terrama2/services/analysis/core/grid/zonal/Operator.cpp
- src/terrama2/services/analysis/core/python/PythonBindingGrid.cpp
- src/terrama2/services/appserver/main.cpp
- src/unittest/core/main.cpp
overload for history grid operators
> Fix compilation error in mac

- webapp/core/FileRequest.js
- webapp/core/FtpRequest.js
- webapp/core/PostgisRequest.js
- webapp/locales/en.json
- webapp/package.json
The only one that I haven't improved yet was the http one, after finishing it, I'll create another pull request.
After updating your app with these changes, you have to run the following commands:
npm prune // This will remove from your app the old package that is not in use anymore
npm install // This will install the new package
> Improving 'Check Connection' buttons

- webapp/core/facade/tcp-manager/TcpService.js
Issue: [564](https://trac.dpi.inpe.br/terrama2/ticket/564)
> Fixing service initialization

- webapp/bin/www
- webapp/core/Application.js
- webapp/core/Process.js
- webapp/core/TcpManager.js
- webapp/core/executors/Local.js
- webapp/core/executors/SSH.js
- webapp/core/facade/tcp-manager/TcpService.js
- webapp/package.json
- webapp/public/javascripts/angular/services/service.js
- webapp/sockets/TcpSocket.js
Issue: [858](https://trac.dpi.inpe.br/terrama2/ticket/858)
> adding support for retrieving TerraMA² service version

- webapp/core/DataManager.js
- webapp/public/javascripts/angular/data-series/data-series.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/geo/app.js
- webapp/public/javascripts/angular/geo/directives.js
- webapp/public/stylesheets/terrama2.css
- webapp/views/administration/users.html
- webapp/views/configuration/alerts.html
- webapp/views/configuration/analysis_list.html
- webapp/views/configuration/dynamicDataSeries.html
- webapp/views/configuration/projects.html
- webapp/views/configuration/providers.html
- webapp/views/configuration/staticData.html
- webapp/views/configuration/views.html
> WebApp fixes

- webapp/locales/en_US.json
- webapp/public/javascripts/angular/data-series/registration.js
> Enable optional form when updating

- src/terrama2/impl/DataAccessorDcpToa5.cpp
- src/terrama2/impl/DataAccessorDcpToa5.hpp
- src/terrama2/impl/DataAccessorFile.cpp
Implemented mask for folders and files in Toa5 archives collector.
> Fix TOA5 collection

- webapp/locales/en_US.json
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/data-series/schedule.js
- webapp/public/javascripts/angular/geo/app.js
- webapp/public/javascripts/angular/geo/directives.js
- webapp/public/javascripts/angular/geo/services.js
- webapp/public/javascripts/angular/wizard.html
- webapp/public/stylesheets/terrama2.css
- webapp/views/configuration/dataset.html
> Fix checks to validate steps when create or update a dynamic data

- share/terrama2/semantics.json
- webapp/core/DataManager.js
- webapp/locales/en_US.json
- webapp/models/DataSeriesSemantics.js
- webapp/public/javascripts/angular/advanced.html
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/data-series/templates/storager.html
**Note**
Delete table _data_series_semantics_ to create the new column _allow_direct_access_
> 904 required store form

- share/terrama2/semantics.json
- webapp/controllers/api/DataSeriesSemantics.js
> Fixing semantics json

- share/terrama2/semantics.json
- src/terrama2/core/Typedef.hpp
- src/terrama2/core/utility/Utils.cpp
- src/terrama2/core/utility/Utils.hpp
- src/terrama2/impl/DataAccessorDcpToa5.cpp
- src/terrama2/impl/DataAccessorFile.cpp
- src/terrama2/impl/DataAccessorFile.hpp
- src/terrama2/impl/DataAccessorGrADS.cpp
- src/terrama2/impl/DataAccessorGrADS.hpp
- src/terrama2/impl/DataStoragerTiff.cpp
- src/terrama2/services/analysis/core/MonitoredObjectContext.cpp
- src/terrama2/services/view/core/Utils.cpp
- webapp/controllers/api/DataSeries.js
- webapp/core/DataManager.js
- webapp/core/Enums.js
- webapp/core/Utils.js
- webapp/locales/en.json
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/generalData.html
- webapp/public/javascripts/angular/services.js
- webapp/public/stylesheets/terrama2.css
Adds new parameters for GRADS format
Persistence with of GeoTIFF files with the folder option
> New parameters for GrADS

- webapp/public/javascripts/angular/analysis/controllers/register-update.js
> Filter dataseries to store to show only dynamic temporality

- src/examples/collector/IntersectionGrid.cpp
- src/terrama2/core/data-model/Filter.hpp
- src/terrama2/core/utility/JSonUtils.cpp
- src/terrama2/impl/DataAccessorFile.cpp
- src/terrama2/impl/DataAccessorFile.hpp
- src/terrama2/impl/DataAccessorGeoTiff.cpp
- src/terrama2/impl/DataAccessorGeoTiff.hpp
- src/terrama2/impl/DataAccessorGrADS.cpp
- src/terrama2/impl/DataAccessorGrADS.hpp
- src/terrama2/impl/DataAccessorStaticGeoTiff.cpp
- src/terrama2/impl/DataAccessorStaticGeoTiff.hpp
- src/terrama2/services/appserver/main.cpp
- src/terrama2/services/collector/core/IntersectionOperation.cpp
- src/terrama2/services/collector/core/IntersectionOperation.hpp
- When intersecting a raster, filter by band
- When collecting Raster, crop by filter region
-----------------------
- better catch for program options errors 
- change in signature of completeDataSet methods to te::mem::DataSet
> Filter and crop raster

- webapp/core/DataManager.js
- webapp/core/data-model/Filter.js
- webapp/locales/en_US.json
- webapp/models/Filter.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/geo/directives.js
**Obs:**
- When accepted this PR, must delete database to include the new column - or run a script to add the column
> 923 add crop field

- webapp/core/data-model/DataProvider.js
- webapp/public/javascripts/angular/data-provider/registration.js
> Remove redundant decode of uri

- share/terrama2/semantics.json
- webapp/public/javascripts/angular/data-series/registration.js
> 930 turn conditional fields when creating grads data

- share/terrama2/semantics.json
- webapp/locales/en_US.json
- webapp/locales/pt_BR.json
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/data-series/templates/intersection.html
- webapp/views/configuration/dataset.html
> 921 intersection improvements

- webapp/public/javascripts/angular/advanced.html
- webapp/public/javascripts/angular/alert-box/directives.js
- webapp/public/javascripts/angular/alert-box/services.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/generalData.html
- webapp/public/javascripts/angular/wizard.html
- webapp/views/configuration/dataset.html
> 941 message box fix

- webapp/core/Enums.js
- webapp/core/facade/tcp-manager/TcpService.js
- webapp/public/javascripts/angular/status/status.js
- webapp/public/stylesheets/terrama2.css
- webapp/views/configuration/status.html
> Return map server layer link of created layer on View service

- webapp/controllers/api/DataSeries.js
> Saving a data series disabled fix

- src/terrama2/core/data-access/DataAccessor.cpp
- src/terrama2/core/data-access/DataAccessor.hpp
- src/terrama2/impl/DataAccessorAnalysisPostGIS.cpp
- src/terrama2/impl/DataAccessorAnalysisPostGIS.hpp
- src/terrama2/impl/DataAccessorMonitoredObjectAnalysisPostGIS.cpp
- src/terrama2/impl/DataAccessorMonitoredObjectAnalysisPostGIS.hpp
- src/terrama2/impl/DataAccessorPostGIS.cpp
- src/terrama2/impl/DataAccessorPostGIS.hpp
- src/terrama2/impl/DataAccessorStaticDataPostGIS.hpp
If the terrama2 dataset don't have the timestamp property informed, try to get this info from te::dataset.
> Datetime column for postGIS dataset

- README.md
- src/examples/collector/CollectorServiceFromFileToCSV.cpp
- src/examples/core/AccessAndFilterOccurrenceMvfFromLocalFolder.cpp
- src/examples/core/AccessAndFilterOccurrenceMvfFromLocalFolderToCSV.cpp
- src/terrama2/impl/DataStoragerCSV.cpp
- src/terrama2/impl/DataStoragerCSV.hpp
- src/terrama2/impl/DataStoragerPostGIS.cpp
- src/terrama2/impl/DataStoragerPostGIS.hpp
- src/terrama2/impl/DataStoragerTable.cpp
- src/terrama2/impl/DataStoragerTable.hpp
- src/terrama2/impl/Utils.cpp
- src/terrama2/services/collector/core/Service.cpp
- DataStoragerCSV and examples
- Small fix in README.md
- Remove unnecessary check
> DataStoragerCSV

- webapp/public/javascripts/angular/data-series/registration.js
Parse to float when prepare fields to fill form on update
> Parse to float fix

- webapp/public/javascripts/angular/analysis/controllers/register-update.js
- webapp/sockets/ImportExport.js
- webapp/views/configuration/analysis.html
> Analisys fix

- share/terrama2/semantics.json
> Adding regex for Mask in semantics

- webapp/public/javascripts/angular/analysis/controllers/register-update.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/data-series/schedule.js
- webapp/public/javascripts/angular/data-series/templates/schedule.html
> Analysis and data series fixes

- share/terrama2/semantics.json
- webapp/core/DataManager.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/data-series/templates/storager.html
- webapp/public/javascripts/angular/dcpTable.html
- webapp/public/stylesheets/terrama2.css
> Adding semantics for active field in DataSet Dcp

- webapp/public/javascripts/angular/alert-box/directives.js
- webapp/public/javascripts/angular/alert-box/services.js
- webapp/public/javascripts/angular/collapser/directives.js
- webapp/public/javascripts/angular/services/registration.js
- webapp/views/administration/service.html
> webapp changes: defining common error display

- webapp/controllers/api/DataSeries.js
- webapp/core/DataManager.js
- webapp/core/Exceptions.js
- webapp/public/javascripts/angular/advanced.html
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/data-series/templates/storager.html
- webapp/public/javascripts/angular/wizard.html
> Store dynamic data series improvements

- webmonitor/bin/www
- webmonitor/config/config.terrama2monitor
- webmonitor/routes/index.js
- webmonitor/views/index.html
- Config file with web app host info to socket connection
> Config file on web monitor project

- src/terrama2/core/utility/Utils.cpp
- src/terrama2/core/utility/Utils.hpp
- src/terrama2/impl/DataAccessorGrADS.cpp
- src/terrama2/impl/DataAccessorGrADS.hpp
Creating a new raster with values in double from another raster.
> Fix truncate rasters values when working with double

- webapp/models/DataSet.js
Ticket: [995](https://trac.dpi.inpe.br/terrama2/ticket/995)
> Fixing static data update

- webapp/locales/en_US.json
- webapp/public/javascripts/angular/analysis/controllers/register-update.js
> Sorting dataSeriesGroup to select in analysis

- build/cmake/CMakeLists.txt
- build/cmake/modules/FindQuaZip.cmake
- share/terrama2/semantics.json
Add FindQuaZip to module folder and fix find package for quazip
> Fix mask for DCP dataset

- share/terrama2/semantics.json
- src/terrama2/core/network/TcpManager.hpp
- src/terrama2/core/utility/CurlPtr.cpp
Adds an '/' to the end of the url when trying to list the files in a directory
> Change bytes before field to always appear

- src/terrama2/services/analysis/core/grid/history/Operator.hpp
- src/terrama2/services/analysis/core/grid/zonal/history/Operator.cpp
- src/terrama2/services/analysis/core/python/PythonBindingGrid.cpp
- src/terrama2/services/analysis/core/python/PythonBindingGrid.hpp
Ticket [976](https://trac.dpi.inpe.br/terrama2/ticket/976)
> Reviewing grid operators signature

- webapp/controllers/api/DataSeries.js
- webapp/core/DataManager.js
- webapp/core/data-model/AnalysisDataSeries.js
- webapp/locales/en_US.json
Show the analysis that use the data series when remove the data series
> Block data series removal

- webapp/controllers/api/DataSeries.js
> Fix collector var name to get collector id

- webapp/locales/en_US.json
- webapp/public/javascripts/angular/advanced.html
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/templates/terrama2-wizard.html
Block the intersection tab until the store form is filled.
> Block intersection tab on dynamic data series creation

- src/terrama2/services/analysis/core/Analysis.hpp
- src/terrama2/services/analysis/core/AnalysisExecutor.cpp
- src/terrama2/services/analysis/core/python/PythonInterpreter.cpp
- src/terrama2/services/analysis/core/utility/JSonUtils.cpp
- src/terrama2/services/analysis/core/utility/Verify.cpp
- src/terrama2/services/analysis/core/utility/Verify.hpp
- webapp/public/javascripts/angular/analysis/data/operators.json
> Remove duplicated log messages

- src/examples/alert/NumericRisk.cpp
- src/terrama2/core/utility/ProcessLogger.hpp
- src/terrama2/core/utility/Service.cpp
- src/terrama2/core/utility/Service.hpp
- src/terrama2/services/alert/core/RunAlert.cpp
- src/terrama2/services/alert/core/RunAlert.hpp
- src/terrama2/services/alert/core/Service.cpp
- src/terrama2/services/alert/core/Service.hpp
- src/terrama2/services/analysis/core/AnalysisExecutor.cpp
- src/terrama2/services/analysis/core/AnalysisExecutor.hpp
- src/terrama2/services/analysis/core/Service.cpp
- src/terrama2/services/analysis/core/Service.hpp
- src/terrama2/services/analysis/core/python/PythonInterpreter.cpp
- src/terrama2/services/collector/core/Service.cpp
- src/terrama2/services/collector/core/Service.hpp
- src/terrama2/services/view/core/Service.cpp
- src/terrama2/services/view/core/Service.hpp
- webapp/core/Enums.js
- webapp/public/javascripts/angular/status/status.js
Refactoring services to use the same process queue
> Creating status on queue

- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/datetimepicker/directive.js
- webapp/views/configuration/dataset.html
Fix language datetime picker
Filter services to create dynamic data series
Parsing correctly store values when updating a data series
> Small fixes

- webapp/public/javascripts/angular/analysis/controllers/list.js
- webapp/public/javascripts/angular/analysis/controllers/register-update.js
- webapp/public/stylesheets/terrama2.css
- webapp/views/configuration/analysis.html
> Adding support to validate analysis only when service is running

- src/terrama2/services/analysis/core/OperatorCache.hpp
- src/terrama2/services/analysis/core/grid/zonal/forecast/accum/Operator.cpp
- src/terrama2/services/analysis/core/grid/zonal/forecast/accum/Operator.hpp
- src/terrama2/services/analysis/core/utility/Utils.cpp
Using boost accumulators for statistics
> Fix implementation of forecast accum operators

- webapp/core/FtpRequest.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/wizard.html
- Fixing the bug in the ftp data provider connection check. (Ticket https://trac.dpi.inpe.br/terrama2/ticket/969#propertyform)
- Hide and show 'next' and 'previous' buttons in the wizard. (Ticket https://trac.dpi.inpe.br/terrama2/ticket/965)
> Bugs fixes

- webapp/core/DataManager.js
- webapp/core/data-model/ViewStyleLegend.js
- webapp/core/facade/tcp-manager/TcpService.js
- webapp/models/ViewStyleLegend.js
- webapp/public/javascripts/angular/views/controllers/view-register-update.js
- webapp/public/javascripts/angular/views/templates/style.html
Ticket
[1032](https://trac.dpi.inpe.br/terrama2/ticket/1032)
> Adding Dummy value in GRID view registration

- webcomponents/javascripts/src/components/MapDisplay.TerraMA2WebComponents.js
- webmonitor/public/javascripts/app.js
- webmonitor/public/javascripts/utils/slider.js
- webmonitor/public/stylesheets/style.css
- webmonitor/views/index.html
- webmonitor/views/layout.html
> Setting layer opacity

- src/terrama2/impl/DataAccessorFile.cpp
- src/terrama2/services/analysis/core/Service.cpp
- src/terrama2/services/collector/core/Service.cpp
- src/terrama2/services/view/core/Service.cpp
> better error treatment

- webmonitor/views/index.html
Fix opacity layer slider when changed the temporal layer.
> Fix opacity layer slider

- webapp/public/javascripts/angular/advanced.html
- webapp/public/javascripts/angular/wizard.html
Temporary using storager form template to load with page
> Temporary using storager template to load with page

- src/terrama2/core/utility/TimeUtils.cpp
[Ticket #1048](https://trac.dpi.inpe.br/terrama2/ticket/1048)
> 	Rollback of time string parser

- webapp/core/DataManager.js
- webapp/core/facade/View.js
- webapp/public/javascripts/angular/data-series/schedule.js
- webapp/public/javascripts/angular/views/controllers/view-register-update.js
- webapp/public/javascripts/angular/views/templates/style.html
> Fixing optional schedule in view dynamic data series

- README.md
- webapp/README.md
- webapp/sockets/ImportExport.js
> Project import fix

- src/terrama2/core/utility/TimeUtils.cpp
- src/terrama2/services/analysis/core/OperatorCache.hpp
Using NAN as result for operators with no data
> Fix unit conversion for one character units("d", "s", ...)

- share/terrama2/semantics.json
- webapp/locales/en_US.json
- webapp/locales/pt_BR.json
- webapp/public/javascripts/angular/analysis/controllers/index.js
- webapp/public/javascripts/angular/data-series/controllers.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/schema-form-plugin/mask-warn/directives/terrama2-mask-field.js
- webapp/public/javascripts/angular/schema-form-plugin/mask-warn/module.js
- webapp/public/javascripts/angular/schema-form-plugin/mask-warn/templates/terrama2-mask-field.html
- webapp/public/stylesheets/terrama2.css
> Schema form add-on to create mask field

- src/terrama2/core/data-access/SynchronizedDataSet.cpp
- src/terrama2/core/data-access/SynchronizedDataSet.hpp
- src/terrama2/services/analysis/core/MonitoredObjectContext.hpp
- src/terrama2/services/analysis/core/occurrence/Operator.cpp
- src/terrama2/services/analysis/core/python/PythonInterpreter.cpp
- src/terrama2/services/analysis/core/python/PythonInterpreter.hpp
- webapp/public/javascripts/angular/analysis/data/operators.json
[Ticket 966](https://trac.dpi.inpe.br/terrama2/ticket/966)
> Adding operator to return an attribute of the monitored object

- share/terrama2/semantics.json
- webapp/controllers/configuration/Views.js
- webapp/core/Enums.js
- webapp/locales/en_US.json
- webapp/locales/pt_BR.json
- webapp/public/javascripts/angular/analysis/controllers/register-update.js
- webapp/public/javascripts/angular/common/directives/datetime.js
- webapp/public/javascripts/angular/data-series/components/storager.js
- webapp/public/javascripts/angular/data-series/schedule.js
- webapp/public/javascripts/angular/data-series/templates/schedule.html
- webapp/public/javascripts/angular/views/controllers/view-register-update.js
- webapp/views/configuration/analysis.html
- webapp/views/configuration/dataset.html
- webapp/views/configuration/view.html
- Removed tag to validate mask pattern until the bind error when editing a data series is resolved.
> New schedule component

- share/terrama2/semantics.json
- src/examples/analysis/ListenToTcpAndRunAnalysis.cpp
- src/examples/analysis/OperatorDCP.cpp
- src/examples/analysis/OperatorHistoryDCP.cpp
- src/examples/analysis/OperatorHistoryIntervalDCP.cpp
- src/terrama2/core/utility/ProcessLogger.cpp
- src/terrama2/core/utility/Utils.cpp
- src/terrama2/core/utility/Verify.cpp
- src/terrama2/core/utility/Verify.hpp
- src/terrama2/impl/DataAccessorFile.cpp
- src/terrama2/impl/DataStoragerTiff.cpp
- src/terrama2/impl/DataStoragerTiff.hpp
- src/terrama2/services/collector/core/IntersectionOperation.cpp
- src/unittest/collector/IntRasterTs.cpp
- src/unittest/collector/main.cpp
The code was updated to use Terralib 5.2, please update.
> update terralib to release 5.2

- src/examples/core/AccessAndStoreOccurrenceGenericFromLocalByColumns.cpp
- src/terrama2/impl/DataAccessorCSV.cpp
- src/terrama2/impl/DataAccessorCSV.hpp
Accessing a generic csv occurrence file based on column position
> refactor DataAccessorCSV

- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/data-series/templates/csvFormat.html
Fix fields json stringify to not save hash key of object in the database;
Change field_type model name to default_type, to follow the documentation.
> Fix fields json stringify, fix default type property name

- build/cmake/terrama2_unittest_collector/CMakeLists.txt
- src/examples/core/AccessAndStoreOccurrenceGenericFromLocalByColumns.cpp
- src/terrama2/core/utility/DataRetrieverFactory.cpp
- src/terrama2/impl/DataAccessorCSV.cpp
- src/terrama2/impl/DataAccessorCSV.hpp
- src/unittest/collector/IntRasterTs.cpp
- src/unittest/collector/main.cpp
review of the collector integration test 
using test data in jenkins ftp
> Collector test

- webapp/bin/webapp-stop.js
It fixes stop services while removing TerraMA² package
> fixing script for stop terrama2 services

- webapp/locales/en_US.json
- webapp/public/javascripts/angular/data-series/components/csvFieldDetail.js
- webapp/public/javascripts/angular/data-series/components/csvFormat.js
- webapp/public/javascripts/angular/data-series/templates/csvFieldDetail.html
- webapp/public/javascripts/angular/data-series/templates/csvFormat.html
- webapp/public/javascripts/angular/wizard.html
> Validations and restrictions of csv format form

- src/examples/alert/NumericRisk.cpp
- src/examples/archiver/KeepLastData.cpp
- src/examples/core/AccessLastDcpInpeFromLocal.cpp
- src/examples/core/AccessLastOccurrenceFromPostGis.cpp
- src/terrama2/core/data-model/Filter.hpp
- src/terrama2/core/utility/JSonUtils.cpp
- src/terrama2/impl/DataAccessorPostGIS.cpp
- src/terrama2/services/alert/core/RunAlert.cpp
- src/terrama2/services/analysis/core/AnalysisExecutor.cpp
- src/terrama2/services/analysis/core/AnalysisExecutor.hpp
- src/terrama2/services/analysis/core/dcp/zonal/Operator.cpp
- src/terrama2/services/analysis/core/grid/Operator.cpp
- src/terrama2/services/analysis/core/grid/forecast/Operator.cpp
- src/terrama2/services/analysis/core/grid/zonal/Operator.cpp
- src/terrama2/services/analysis/core/grid/zonal/forecast/Operator.cpp
- src/terrama2/services/analysis/core/grid/zonal/forecast/accum/Operator.cpp
- src/terrama2/services/analysis/core/utility/Utils.cpp
- src/terrama2/services/collector/core/IntersectionOperation.cpp
- Including Foreign Key of monitored objects in analysis
- alert uses dataset Foreign Key to identify monitored objects id
> Partially Working example NumericRisk

- src/terrama2/core/utility/Utils.cpp
- src/terrama2/impl/DataAccessorFile.cpp
- src/terrama2/services/alert/core/RunAlert.cpp
Fix hash generation and filter by date
> Fix grid analysis

- build/cmake/terrama2_core/CMakeLists.txt
- src/examples/core/DataRetrieverFromFTP.cpp
- src/examples/core/RetrieverFromSindaFTP.cpp
- src/terrama2/core/data-access/DataRetriever.cpp
- src/terrama2/core/data-access/DataRetriever.hpp
- src/terrama2/core/utility/TerraMA2Init.cpp
- src/terrama2/impl/DataAccessorFile.cpp
- src/terrama2/impl/DataAccessorGrADS.cpp
- src/terrama2/impl/DataRetrieverFTP.cpp
- src/terrama2/impl/DataRetrieverFTP.hpp
- src/terrama2/services/appserver/main.cpp
- src/unittest/core/MockDataRetriever.hpp
- src/unittest/core/TsDataAccessorDcpInpe.cpp
- src/unittest/core/TsDataAccessorDcpToa5.cpp
- src/unittest/core/TsDataAccessorGDAL.cpp
- src/unittest/core/TsDataAccessorOccurrenceWfp.cpp
- src/unittest/core/TsDataRetrieverFTP.cpp
The DataRetriever wasn't using the timezone, this fix the issue
> Get timezone from dataset

- build/cmake/terrama2_core/CMakeLists.txt
- src/terrama2/core/utility/TerraMA2Init.cpp
- src/terrama2/services/analysis/core/grid/zonal/forecast/Operator.cpp
- src/terrama2/services/analysis/core/grid/zonal/forecast/Operator.hpp
- src/terrama2/services/analysis/core/grid/zonal/forecast/interval/Operator.cpp
- src/terrama2/services/analysis/core/grid/zonal/forecast/interval/Operator.hpp
- src/terrama2/services/analysis/core/python/PythonBindingGrid.cpp
- src/terrama2/services/appserver/main.cpp
- webapp/public/javascripts/angular/analysis/data/grid-monitored-operators.json
Num and List operators for:
- grid zonal forecast
- grid zonal forecast interval
> Analysis operators

- webapp/public/javascripts/angular/alerts/controllers/alert-list.js
- webapp/public/javascripts/angular/services/registration.js
- webapp/public/javascripts/angular/services/service.js
Alert run button;
Saving alert email server;
> Alert run button

- webapp/core/DataManager.js
- webapp/core/data-model/Service.js
- webapp/models/ServiceInstance.js
- webapp/public/javascripts/angular/services/registration.js
Decode email username;
Remove maps_server_uri from service_instances table;
Fix email uri when save alert service;
Actualize database with the follow script:
ALTER TABLE terrama2.service_instances DROP COLUMN maps_server_uri
> Alert service fixes

- webapp/public/javascripts/angular/analysis/controllers/register-update.js
- webapp/public/javascripts/angular/services/registration.js
- webapp/public/javascripts/angular/views/controllers/view-register-update.js
> 1154 schedule error

- build/cmake/CMakeLists.txt
- build/cmake/terrama2_alert_impl/CMakeLists.txt
- build/cmake/terrama2_service/CMakeLists.txt
- src/terrama2/services/alert/impl/Utils.cpp
- src/terrama2/services/appserver/main.cpp
vmime optional to alert service
> Cmake defines to allow terrama2 compilation without all the modules,

- webapp/controllers/api/Analysis.js
- webapp/controllers/api/DataSeries.js
- webapp/controllers/api/View.js
- webapp/core/facade/Analysis.js
- webapp/core/facade/View.js
- webapp/public/javascripts/angular/analysis/controllers/list.js
- webapp/public/javascripts/angular/data-series/data-series.js
- webapp/public/javascripts/angular/views/controllers/view-list.js
- webapp/sockets/TcpSocket.js
- webapp/views/configuration/analysis_list.html
- webapp/views/configuration/views.html
> Services error messages

- build/cmake/CMakeLists.txt
- build/cmake/terrama2_alert_impl/CMakeLists.txt
- src/terrama2/core/data-model/DataSetDcp.hpp
- src/terrama2/core/data-model/Filter.hpp
- src/terrama2/core/utility/JSonUtils.cpp
- src/terrama2/core/utility/ServiceManager.cpp
- src/terrama2/core/utility/Utils.cpp
- src/terrama2/services/alert/impl/DocumentPDF.hpp
- src/terrama2/services/collector/core/JSonUtils.cpp
- webapp/public/javascripts/angular/analysis/controllers/list.js
- webapp/public/javascripts/angular/data-series/data-series.js
- webapp/public/javascripts/angular/views/controllers/view-list.js
remove unused attribute
remove old TODO's
> fix filter from json

- webapp/models/Alert.js
- webapp/models/ReportMetadata.js
- webapp/models/Risk.js
- webapp/public/javascripts/angular/alerts/controllers/alert-register-update.js
- webapp/public/javascripts/angular/alerts/services/alert.js
- webapp/public/javascripts/angular/views/services/view.js
- webapp/views/configuration/alert.html
Change description type of Alert, Report Metadata and Risk to TEXT;
Fixing behavior of alert registration screen when updating an alert;
When get this PR drop your database or run the follow script:
```
ALTER TABLE terrama2.report_metadata ALTER COLUMN description TYPE TEXT;
ALTER TABLE terrama2.risks ALTER COLUMN description TYPE TEXT;
ALTER TABLE terrama2.alerts ALTER COLUMN description TYPE TEXT;
```
> Fixing view and alert update

- webapp/public/javascripts/angular/data-series/components/storager.js
> Don't show ftp providers in store options

- src/terrama2/services/appserver/main.cpp
allow usage of qt program args
> Prepare to no display execution

- share/terrama2/semantics.json
- webapp/core/FtpRequest.js
- webapp/core/Utils.js
- webapp/public/javascripts/angular/geo/directives.js
> Number fields validation

- build/cmake/terrama2_unittest_view/CMakeLists.txt
- src/examples/analysis/ListenToTcpAndRunAnalysis.cpp
- src/examples/collector/ListenToTcpAndCollect.cpp
- src/examples/core/ProcessLogger.cpp
- src/terrama2/core/data-access/DataAccessor.cpp
- src/terrama2/core/utility/ProcessLogger.cpp
- src/terrama2/core/utility/Raii.hpp
- src/terrama2/core/utility/Service.cpp
- src/terrama2/core/utility/Unpack.cpp
- src/terrama2/core/utility/Utils.cpp
- src/terrama2/impl/DataAccessorCSV.cpp
- src/terrama2/impl/DataAccessorDcpInpe.cpp
- src/terrama2/impl/DataAccessorDcpToa5.cpp
- src/terrama2/impl/DataAccessorOccurrenceLightning.cpp
- src/terrama2/impl/DataAccessorOccurrenceWfp.cpp
- src/terrama2/impl/DataRetrieverFTP.cpp
- src/terrama2/services/alert/core/AlertExecutor.cpp
- src/terrama2/services/alert/core/DataManager.cpp
- src/terrama2/services/alert/core/Service.cpp
- src/terrama2/services/analysis/core/AnalysisExecutor.cpp
- src/terrama2/services/analysis/core/DataManager.cpp
- src/terrama2/services/analysis/core/Service.cpp
- src/terrama2/services/appserver/main.cpp
- src/terrama2/services/collector/core/DataManager.cpp
- src/terrama2/services/collector/core/Service.cpp
- src/terrama2/services/view/core/DataManager.cpp
- src/terrama2/services/view/core/MemoryDataSetRenderer.cpp
- src/terrama2/services/view/core/Service.cpp
- src/terrama2/services/view/core/View.hpp
- src/unittest/view/TsJsonUtils.cpp
read te::Exception with boost,
std and ... as last catch
> fix exception

- webapp/views/configuration/alert.html
- webmonitor/public/javascripts/app.js
- Remove txt type when generate an alert report
- Change web monitor type icons
> Remove txt type when generate an alert report

- webapp/public/javascripts/angular/analysis/controllers/register-update.js
- webapp/public/javascripts/angular/analysis/directives.js
- webapp/views/configuration/analysis.html
Added button to list data series attributes when create an analysis script;
> Button to list data series attributes

- webapp/public/javascripts/angular/ace/directive.js
- webapp/public/javascripts/angular/analysis/controllers/register-update.js
- webapp/views/configuration/analysis.html
Changed ace and analysis helpers directives to insert code value in cursor
> Insert script code at cursor

- src/terrama2/impl/DataAccessorGDAL.cpp
Some raster, like ascii-grid, dont have an srid but the user can configure that.
Here we set an srid but there is a bug in TerraLib so it doesn't solve the problem.
> set srid in raster read

- webapp/config/config.terrama2
- webapp/controllers/api/Project.js
> Creating defaults postgis and file data providers

- webapp/public/javascripts/angular/analysis/controllers/register-update.js
- webapp/public/javascripts/angular/analysis/directives.js
- webapp/public/javascripts/angular/collapser/directives.js
- webapp/public/stylesheets/terrama2.css
- webapp/views/configuration/analysis.html
[1240](https://trac.dpi.inpe.br/terrama2/ticket/1240)
> Fixing max-height to attributes list

- webapp/config/config.terrama2
- webapp/public/javascripts/angular/data-provider/controllers/registration.js
[1238](https://trac.dpi.inpe.br/terrama2/ticket/1238)
> Change default file path

- webapp/locales/en_US.json
- webapp/locales/pt_BR.json
- webapp/public/javascripts/angular/data-series/templates/intersection.html
- webapp/public/stylesheets/terrama2.css
> Select at least one attribute

- src/terrama2/core/utility/Utils.cpp
dummy value was beeing multiplied.
> Fix grads multiplier

- share/terrama2/semantics/grid-gdal.json
> Add asc-grid semantics

- build/cmake/CMakeLists.txt
- scripts/postinst.in
- src/terrama2/services/alert/core/AlertExecutor.cpp
- src/terrama2/services/alert/core/AlertExecutor.hpp
- src/terrama2/services/alert/core/Report.cpp
- src/terrama2/services/alert/core/Report.hpp
- src/terrama2/services/alert/core/Service.cpp
- src/terrama2/services/view/core/Service.cpp
fix: remove unexisting process
> #1295 Fix make install

- src/terrama2/services/view/core/MemoryDataSetLayer.cpp
- src/terrama2/services/view/core/data-access/Geoserver.cpp
> Fixing GeoServer Style generation with opacity

- src/terrama2/services/alert/core/Report.cpp
- src/terrama2/services/alert/core/Report.hpp
> Get max and min value on alert raster

- share/terrama2/semantics/grid-gdal.json
- webapp/locales/en_US.json
- webapp/locales/es_ES.json
- webapp/locales/pt_BR.json
- webapp/public/javascripts/angular/data-series/components/storager.js
> Geotiff extension

- webapp/sockets/ImportExport.js
Updating "monitored_object_id" key of data set format
> Fix analysis import

- webapp/public/javascripts/angular/alerts/controllers/alert-list.js
> Show service name on error response

- webapp/core/DataManager.js
Creating default services only when don't have any services on db.
> Fix auto services creation

- src/terrama2/impl/DataAccessorOccurrenceLightning.cpp
- src/terrama2/impl/DataAccessorPostGIS.cpp
- src/terrama2/impl/DataStoragerPostGIS.cpp
- src/terrama2/impl/DataStoragerTable.cpp
- src/terrama2/impl/DataStoragerTable.hpp
- src/terrama2/services/view/core/data-access/Geoserver.cpp
- src/unittest/core/TsDataAccessorDcpToa5.cpp
Solves the problem with filter string in analysis operations,
Improvements of the code,
creating spatial index,
re-include code wrongly removed
> remove unneeded protection

- webapp/core/facade/View.js
- webapp/core/facade/tcp-manager/TcpService.js
- webapp/sockets/ViewSocket.js
- webmonitor/public/javascripts/TerraMA2WebMonitor.js
> Remove layer in monitor

- webapp/core/data-model/RegisteredView.js
- webapp/sockets/ViewSocket.js
- webmonitor/public/javascripts/TerraMA2WebMonitor.js
- webmonitor/public/javascripts/components/Layers.js
- webmonitor/views/index.html
> List layers by project

- src/examples/core/DataRetrieverFromFTP.cpp
- src/examples/core/RetrieverFromSindaFTP.cpp
- src/terrama2/core/utility/Service.cpp
small fix in processing threads creation
> 	remove passwords from examples

- build/cmake/terrama2_core/CMakeLists.txt
- build/cmake/terrama2_examples_core/CMakeLists.txt
- src/examples/core/PythonInterpreter.cpp
- src/terrama2/core/interpreter/Interpreter.hpp
- src/terrama2/core/interpreter/PythonInterpreter.cpp
- src/terrama2/core/interpreter/PythonInterpreter.hpp
Simple Python Interpreter for uses in other services.
> Python Interpreter class

- src/terrama2/impl/DataAccessorFile.cpp
- src/terrama2/impl/DataStoragerDCPPostGIS.cpp
> Fix error msg in empty inpe dcp,

- src/examples/analysis/NovaFriburgo.cpp
- src/examples/core/RiscoDeFogo.cpp
- src/terrama2/services/analysis/core/AnalysisExecutor.cpp
- src/terrama2/services/analysis/core/AnalysisExecutor.hpp
- src/terrama2/services/analysis/core/BaseContext.hpp
- src/terrama2/services/analysis/core/Service.hpp
Compilation correction with Python library
> Create the new examples Nova Friburgo and Fire Risk

- src/examples/core/ProcessLogger.cpp
- src/terrama2/core/utility/ProcessLogger.cpp
- src/terrama2/core/utility/ProcessLogger.hpp
- src/terrama2/core/utility/Raii.cpp
- src/terrama2/core/utility/Raii.hpp
- src/terrama2/impl/DataAccessorFile.cpp
- src/terrama2/services/analysis/core/occurrence/zonal/Operator.cpp
- src/terrama2/services/view/core/Utils.cpp
- src/terrama2/services/view/core/data-access/DataAccess.cpp
- src/terrama2/services/view/core/data-access/DataAccess.hpp
- src/terrama2/services/view/core/data-access/Geoserver.cpp
- src/unittest/core/MockProcessLogger.hpp
- src/unittest/core/TestLogger.hpp
- src/unittest/core/TsProcessLogger.cpp
- src/unittest/core/main.cpp
Review datasource open/close connection,
create auxiliary functions to close on destruction and review code usage.
> review raii connection

- webapp/core/DataManager.js
- webapp/core/data-model/Filter.js
- webapp/public/javascripts/angular/geo/app.js
> Getting filter region srid

- webmonitor/app.js
- webmonitor/bin/www
- webmonitor/config/sample_monitor.json
- webmonitor/controllers/CheckGridController.js
- webmonitor/core/Application.js
- webmonitor/routes/index.js
- webmonitor/sockets/State.js
- webmonitor/sockets/ViewsHandler.js
> Change config file accept more the one config settings

- webmonitor/public/javascripts/TerraMA2WebMonitor.js
Fix initial value of slider date of dynamic data, updating slider with new date
> Fix monitor slider dates

- share/terrama2/semantics/geo-obj-ogr.json
- share/terrama2/semantics/geo-obj-postgis.json
- share/terrama2/semantics/static-grid-gdal.json
- webapp/config/Sequelize.js
- webapp/locales/en_US.json
- webapp/locales/es_ES.json
- webapp/locales/pt_BR.json
- webapp/public/javascripts/angular/analysis/controllers/list.js
- webapp/public/javascripts/angular/analysis/controllers/register-update.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/views/configuration/analysis.html
Don't sending convert_all as null to service
Adjusts of release 1 test
> Tests fixes

- webapp/core/ImportProject.js
Check objects name when import objects
> Check objects name when import

- webapp/core/data-model/DataSeries.js
- webapp/public/javascripts/angular/views/controllers/view-register-update.js
> Checking data series provider type to create a view

- webapp/public/javascripts/angular/alerts/controllers/alert-register-update.js
- webapp/public/javascripts/angular/views/components/style.js
- webapp/public/javascripts/angular/views/controllers/view-register-update.js
- webapp/public/javascripts/angular/views/templates/style.html
Changed legend creation types:
"0" to "editor"
"1" to "xml"
> Changed types of legends

- webapp/core/FtpRequest.js
- webapp/core/HttpRequest.js
- webapp/core/HttpsRequest.js
- webapp/core/Utils.js
- webapp/public/javascripts/angular/data-provider/controllers/registration.js
Remove "/" char if hostname address ends with "/"
> Validate provider address

- webapp/public/javascripts/angular/alerts/controllers/alert-register-update.js
- webapp/public/javascripts/angular/common/services/utility.js
- webapp/public/javascripts/angular/views/components/style.js
- webapp/public/stylesheets/terrama2.css
- webapp/views/configuration/alert.html
Function to convert hex to rgba color and fill modal, fix css fields of legend levels
> Fill rgba modal

- webapp/public/javascripts/angular/views/components/style.js
- webapp/public/javascripts/angular/views/controllers/view-register-update.js
- webapp/public/javascripts/angular/views/templates/style.html
- webapp/views/configuration/view.html
> List columns of postgis data series to create view

- webapp/controllers/administration/Service.js
- webapp/public/javascripts/angular/services/registration.js
- webapp/views/administration/service.html
> Fill service log info

- webapp/scripts/ImportProject.js
> Auto select service when import project by script

- webapp/core/ImportProject.js
> Fix import to save data provider options

- webapp/core/ImportProject.js
> Importing intersections of a data series

- webapp/public/javascripts/angular/projects/controllers/registration.js
> Allow create new project protected

- webapp/controllers/api/DataSeries.js
> Update data provider of analysis data series

- webapp/locales/en_US.json
- webapp/locales/es_ES.json
- webapp/locales/pt_BR.json
- webapp/public/javascripts/angular/views/components/style.js
- webapp/public/javascripts/angular/views/templates/style.html
> Auto legend to grid

- src/terrama2/core/utility/GeoUtils.cpp
- src/terrama2/core/utility/GeoUtils.hpp
- src/terrama2/impl/DataAccessorFile.cpp
- src/terrama2/impl/DataAccessorFile.hpp
- src/terrama2/services/collector/core/IntersectionOperation.cpp
Using an RTree to filter valid data,
before we intersected with every geometry of the dataset
> Filter with rtree

- webapp/public/javascripts/angular/status/status.js
- webapp/public/javascripts/angular/table/table.js
- webapp/public/javascripts/angular/table/templates/tableFilter.html
- webapp/views/configuration/status.html
Changed status column order
Added advanced filter to status
> Status column order and advanced field

- webapp/controllers/administration/User.js
- webapp/controllers/api/Project.js
- webapp/core/DataManager.js
- webapp/core/facade/Project.js
- webapp/locales/en_US.json
- webapp/locales/es_ES.json
- webapp/locales/pt_BR.json
- webapp/public/javascripts/angular/data-series/directives.js
- webapp/public/javascripts/angular/projects/controllers/list.js
- Translations;
- Showing user name in the projects list;
- Fixing user deletion;
- Fixing static files importation messages;
> Fixing bugs

- webmonitor/public/javascripts/TerraMA2WebMonitor.js
> New template layer

- webapp/public/javascripts/angular/services/registration.js
- webapp/views/administration/service.html
> Fix updating not local service

- webapp/public/javascripts/angular/data-series/registration.js
> Fix overwrite of output dataset metadata

- src/terrama2/services/alert/core/AlertExecutor.cpp
- src/terrama2/services/alert/core/JSonUtils.cpp
- src/terrama2/services/analysis/core/python/PythonBindingDCP.cpp
fix typo in dcp.standart_deviation
fix boundingbox of attached images
> Fix small bugs

- webapp/core/data-model/ViewStyleLegend.js
- webapp/public/javascripts/angular/views/controllers/view-register-update.js
> Fix legend view metadata type

- webapp/public/javascripts/angular/data-series/data-series.js
Dont show dcp data series to import data series from another project.
> Filter data series to import

- src/terrama2/core/network/TcpManager.cpp
- src/terrama2/services/alert/core/Alert.hpp
- src/terrama2/services/alert/core/AlertExecutor.cpp
- src/terrama2/services/alert/core/AlertExecutor.hpp
- src/terrama2/services/view/core/data-access/Geoserver.cpp
- fix error handling, services should never return before logging the the process end
- use the monitored object primary key as key in the analysis result.
> Fix alert mo

- src/terrama2/services/view/core/data-access/Geoserver.cpp
> check if the symbolizer was created,

- LINUX.md
- build/cmake/CMakeLists.txt
- build/cmake/modules/FindVMime.cmake
- packages/debian-package/deb-gtest.sh
- packages/debian-package/deb-helper.sh
- packages/debian-package/deb-terrama2.sh
- packages/debian-package/deb-vmime.sh
- webapp/README.md
- webapp/config/sample_instances/default.json
- webapp/locales/en_US.json
- webapp/locales/es_ES.json
- webapp/locales/pt_BR.json
- webcomponents/README.md
- webmonitor/locales/en.json
- webmonitor/locales/es.json
- webmonitor/locales/pt.json
> versioning 4.0.1

- build/cmake/CMakeLists.txt
copy update script to installer
> copy script to share/terrama2/scripts folder,

- src/terrama2/services/alert/core/Utils.cpp
> fix alert precision,

- .gitignore
- src/terrama2/services/alert/core/AlertExecutor.cpp
- src/terrama2/services/alert/core/AlertExecutor.hpp
- src/terrama2/services/alert/core/Report.cpp
- src/terrama2/services/alert/core/Utils.cpp
- null values
- fix monitored object join
- numeric values
> Review alert dataset

- DEPENDENCIES
- LINUX.md
- README.md
- build/cmake/CMakeLists.txt
- build/cmake/modules/FindVMime.cmake
- helper/indice_manual.html
- helper/introduction.html
- packages/debian-package/deb-gtest.sh
- packages/debian-package/deb-helper.sh
- packages/debian-package/deb-terrama2.sh
- packages/debian-package/deb-vmime.sh
- packages/dmg-package/dmg-terrama2.sh
- packages/install.sh
- packages/uninstall.sh
- webapp/config/sample_instances/default.json
- webapp/locales/en_US.json
- webapp/locales/es_ES.json
- webapp/locales/pt_BR.json
- webapp/package.json
- webcomponents/package.json
- webmonitor/locales/en.json
- webmonitor/locales/es.json
- webmonitor/locales/pt.json
- webmonitor/package.json
> versioning terrama 4.0.3

- .gitignore
- build/cmake/terrama2_view_core/CMakeLists.txt
- packages/debian-package/deb-helper.sh
- packages/debian-package/deb-vmime.sh
> versioning vmime and doc packages

- webapp/core/TcpManager.js
- webapp/core/facade/tcp-manager/ProcessFinished.js
- webapp/core/facade/tcp-manager/TcpService.js
Ticket https://trac.dpi.inpe.br/terrama2/ticket/1479
> Don't send start signal to deactivated items / Fixing bugs with automatic schedule

- src/terrama2/core/data-model/Risk.hpp
- src/terrama2/services/alert/core/AlertExecutor.cpp
Default -> <any level> = increased
> improve alert comparison attribute,

- src/terrama2/services/alert/core/AlertExecutor.cpp
invalid comparison result in null
> fix last commit,

- src/terrama2/services/analysis/core/GridContext.cpp
> check if analysis output raster config is valid,

- webapp/public/javascripts/angular/views/components/style.js
- webapp/public/javascripts/angular/views/controllers/view-register-update.js
Ticket: https://trac.dpi.inpe.br/terrama2/ticket/1433
> Improving view style

- webapp/public/javascripts/angular/data-series/registration.js
Ticket: https://trac.dpi.inpe.br/terrama2/ticket/1488
> Fixing dcps bug

- src/terrama2/impl/DataStoragerDCPSingleTable.cpp
- webcomponents/package-lock.json
>  node package-lock for webcomponents

- webapp/controllers/configuration/ViewsRetriever.js
- webapp/core/Service.js
use view description on the webmonitor, except in alert-view
> read data from socket when message greater then packages

- Changelog.md
- install/install-3rdparty-linux-ubuntu-14.04.sh
- install/install-3rdparty-macos-sierra.sh
- packages/debian-package/deb-terrama2.sh
- packages/dmg-package/dmg-terrama2.sh
- src/terrama2/services/analysis/core/grid/forecast/Operator.cpp
- remove clear from scripts to allow reading error messages
- remove warnings
> update changelog + small fixes

- .github/PULL_REQUEST_TEMPLATE.md
The template can be updated by editing the ``.github/PULL_REQUEST_TEMPLATE.md`` file. When you select the **Create pull request** option, the contents of the template will be copied to the description and can be adjusted as needed.
> Adding template for pull requests

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Pull request model by @carolgsantos 
(I merged to the wrong branch and copied here)
> Pull request and issues template

- Changelog.md
- docker/package/Dockerfile
- docker/package/docker.md
- docker/package/entrypoint.sh
- scripts/check-translation-files.py
- scripts/check-translations.py
- webapp/locales/pt_BR.json
- allow docker to generated package from any repository or branch
- small fixes in translation
- add python path to executable scripts
**Type:**
- [] New feature
**Platform:**
<details>
*Enhancement:*
-  allow docker to generated package from any repository or branch
*Bug fix:*
- Improvment in portuguese translation
</details>
> Minor improvements

- Changelog.md
- src/terrama2/impl/DataStoragerDCPPostGIS.cpp
- src/terrama2/impl/DataStoragerDCPPostGIS.hpp
- src/terrama2/services/alert/core/AlertExecutor.cpp
- src/terrama2/services/view/core/data-access/Geoserver.cpp
- webapp/locales/en_US.json
- webapp/locales/es_ES.json
- webapp/locales/pt_BR.json
- webapp/public/javascripts/angular/analysis/controllers/register-update.js
- webapp/public/javascripts/angular/interpolator/templates/wizard.html
- webapp/views/configuration/interpolator.html
Fix crash in alert from analysis dcp
**Type:**
**Platform:**
<details>
*Bug fix:*
- Alert from DCP analysis
</details>
> Analysis dcp alert

- LINUX.md
- build/cmake/CMakeLists.txt
- build/cmake/modules/FindVMime.cmake
- helper/indice_manual.html
- helper/introduction.html
- packages/debian-package/deb-gtest.sh
- packages/debian-package/deb-helper.sh
- packages/debian-package/deb-terrama2.sh
- packages/debian-package/deb-vmime.sh
- webapp/config/sample_instances/default.json
- webapp/locales/en_US.json
- webapp/locales/es_ES.json
- webapp/locales/pt_BR.json
- webapp/package.json
- webcomponents/package.json
- webmonitor/locales/en.json
- webmonitor/locales/es.json
- webmonitor/locales/pt.json
- webmonitor/package.json
Preparing new version of TerraMA² : 4.0.7
**Type:**
**Platform:**
> versioning 4.0.7

- docker/dev/clang_update-alternative.sh
- src/examples/analysis/AnalysisRiscoFogo.cpp
- Translate coments from AnalysisRiscoFogo.cpp to english
- 
add python scripts to update alternatives
**Type:**
**Platform:**
> Translate comments to english, minor improve to docker

- .github/PULL_REQUEST_TEMPLATE.md
Update the pull request model to include Web as a Platform
**Type:**
**Platform:**
<details>
*Enhancement:*
- Update the pull request model to include Web as a Platform
</details>
> update pull request model

- LINUX.md
- VERSIONING.md
- build/cmake/CMakeLists.txt
- build/cmake/modules/FindVMime.cmake
- helper/Introducao.html
- helper/indice_manual.html
- helper/introduction.html
- packages/debian-package/deb-gtest.sh
- packages/debian-package/deb-helper.sh
- packages/debian-package/deb-terrama2.sh
- webapp/config/sample_instances/default.json
- webapp/locales/en_US.json
- webapp/locales/es_ES.json
- webapp/locales/pt_BR.json
- webapp/package.json
- webcomponents/package.json
- webmonitor/locales/en.json
- webmonitor/locales/es.json
- webmonitor/locales/pt.json
- webmonitor/package.json
Versioning 4.0.8
**Type:**
**Platform:**
> Versioning 4.0.8

- webapp/models/Collector.js
Fix import error when collector is null
@janosimas 
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix import error by project ID when collector is null
</details>
> Fix import error when collector is null

- webapp/models/Collector.js
- webapp/public/javascripts/angular/projects/controllers/list.js
- webmonitor/public/javascripts/components/AnimatedLayer.js
merge fixes from 4.0.7 into master
> merge 4.0.7 

- src/terrama2/core/data-model/DataManager.cpp
- src/terrama2/core/data-model/DataManager.hpp
fix updating project data
**Type:**
**Platform:**
<details>
*Bug fix:*
* fix updating project data
</details>
> fix updating project data

- Changelog.md
- share/terrama2/semantics/occurrence-inpe.json
- src/terrama2/impl/DataAccessorOccurrenceWfp.cpp
Update INPE wild fire program access driver
**Type:**
**Platform:**
<details>
*Enhancement:*
* Update INPE wild fire program access driver
</details>
> Wfp update

- webapp/core/DataManager.js
Fix update alert when no view selected
@janosimas 
**Type:**
**Platform:**
<details>
*Bug fix:*
*  Fix update alert when no view selected
</details>
>  Fix update alert when no view selected

- webapp/public/javascripts/angular/data-series/registration.js
Disable update of Dcp Lat/Long fields.
@janosimas 
**Type:**
**Platform:**
<details>
*Bug fix:*
* Disable update of Dcp Lat/Long fields
</details>
> Disable update of Dcp Lat/Long fields

- webapp/bin/www
- webapp/config/Database.js
By default, TerraMA² tries to connect in database `postgres` and then create right database defined in `/config/instances/default.json`. The problem is that in production environment, where has strict access control in databases, you may face problems with `pg_hba.conf` due the user must allow `postgres` database to the user.
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix database initialization - webapp
</details>
> Fix database initialization - webapp

- webapp/core/Service.js
- webapp/core/TcpManager.js
- webapp/core/facade/tcp-manager/TcpService.js
- webapp/sockets/TcpSocket.js
- webmonitor/public/javascripts/TerraMA2WebMonitor.js
- webmonitor/sockets/ViewsHandler.js
Fix component renderization for Service Start and Stop
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix component renderization for Service Start and Stop
</details>
> Fix component renderization for Service Start and Stop

- src/terrama2/core/utility/FilterUtils.cpp
- src/terrama2/impl/DataStoragerTiff.cpp
- webapp/controllers/api/DataSeriesSemantics.js
- webapp/public/javascripts/angular/data-series/services.js
**Working in Progress - Do not merge it**
Review the collector to support Julian day properly
**Type:**
**Platform:**
<details>
*Enhancement:*
* Review Julian day on terrama2 Services
</details>
> WIP: Review Julian day support on terrama2 Services

- Changelog.md
- share/terrama2/semantics/grid-gdal.json
- src/terrama2/core/utility/Unpack.cpp
- src/terrama2/impl/DataAccessorFile.cpp
- src/terrama2/impl/DataAccessorNetCDF.cpp
- src/terrama2/impl/DataAccessorNetCDF.hpp
- src/terrama2/impl/Utils.cpp
- webapp/controllers/api/DataSeries.js
Fix update schedule on data series collector
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix update schedule on data series collector
</details>
> Fix update schedule on data series collector

- webapp/public/javascripts/angular/table/templates/table.html
Updating import/export icons.
@raphaelrpl 
**Type:**
**Platform:**
> Updating import/export icons.

- src/terrama2/core/data-access/DataAccessor.cpp
- src/terrama2/core/utility/Service.cpp
- src/terrama2/impl/DataAccessorGrADS.cpp
- src/terrama2/impl/DataAccessorPostGIS.cpp
- src/terrama2/impl/DataRetrieverHTTP.cpp
- src/terrama2/services/analysis/core/python/PythonInterpreter.cpp
- src/terrama2/services/analysis/core/python/PythonInterpreter.hpp
- webapp/bin/www
- webapp/core/Logger.js
- webapp/core/Service.js
- webapp/core/facade/tcp-manager/TcpService.js
- webapp/package.json
- webapp/public/javascripts/angular/data-series/directives.js
- webapp/sockets/ServicePortChecker.js
- webapp/sockets/TcpSocket.js
This PR aims to solve collector service for semantics GrADS. When Local Data Folder (`DataProvider`), the temporal mask seems not work properly.
It also includes minor fixes such:
- Auto-save when Upload shapefile 
- Fix delete checking on front-end. Now it does not broadcast 
- Fix Analysis Validation (Static Python Error only)
**Type:**
**Platform:**
<details>
*Enhancement:*
* Auto-save when Upload shapefile fbc7d9c
*Bug fix:*
* Fix GrADS for local folder and ftp files  ae61355
* Fix delete checking on front-end. Now it does not broadcast  47c5514
* Fix Analysis Validation (Static Python Error only) e1a4c49
</details>
> Fix GrADS for local folder and ftp files and minor fixes

- share/terrama2/semantics/occurrence-postgis.json
Fix occurrence postgis semantics
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix occurrence postgis semantics
</details>
> Fix occurrence postgis semantics

- webapp/public/javascripts/angular/data-provider/controllers/registration.js
Validating path.
@raphaelrpl 
**Type:**
**Platform:**
> Validating the path informed.

- webapp/core/FileRequest.js
Filling input text with the default path.
@raphaelrpl 
**Type:**
**Platform:**
> Adding default value.

- webapp/bin/www
- webapp/core/executors/Local.js
- webapp/core/facade/tcp-manager/TcpService.js
- webapp/public/javascripts/angular/advanced.html
- webapp/public/javascripts/angular/data-series/components/csvFieldDetail.js
- webapp/public/javascripts/angular/data-series/components/csvFormat.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/data-series/templates/csvFieldDetail.html
- webapp/public/javascripts/angular/data-series/templates/csvFormat.html
- webapp/public/javascripts/angular/wizard.html
- webapp/public/stylesheets/terrama2.css
This PR aims to solve DCP CSV update. The user input a new value and save. The webapp does not persist on database though. In this way, the CSV Component has been reviewed and now its triggering when interface has been interacted and then notify parent component to handle this behavior properly.
It also includes minor fixes like
- Fix unhandled exception on service startup
- Fix firefox dcp table renderization and button alignment.
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix DCP CSV Update fields
* Fix unhandled exception on service startup
* Fix firefox dcp table renderization and button alignment.
</details>
> Bug fix on DCP CSV Update and minor changes

- webapp/public/javascripts/angular/status/status.js
- webapp/views/configuration/status.html
Adding status table improvements.
@raphaelrpl 
**Type:**
**Platform:**
> Linking the status name with the process.

- webapp/public/javascripts/angular/status/status.js
Fixing the process id.
@raphaelrpl 
**Type:**
**Platform:**
> Fixing the process id

- webapp/public/javascripts/angular/status/status.js
Returning empty value when the collector.id is not found.
@raphaelrpl 
**Type:**
**Platform:**
> Returning empty value when the collector.id is not found.

- src/terrama2/impl/DataAccessorCSV.cpp
- src/terrama2/impl/DataAccessorCSV.hpp
- webapp/public/javascripts/angular/analysis/controllers/register-update.js
- webapp/public/javascripts/angular/data-series/services.js
- webapp/sockets/TcpSocket.js
- webapp/views/configuration/analysis.html
Set icon information on analysis data series
**Type:**
**Platform:**
<details>
*Enhancement:*
* Set icon information on analysis data series
</details>
> Set icon information on analysis data series

- webapp/config/sample_instances/default.json
- webapp/controllers/configuration/DataProvider.js
- webapp/core/FileRequest.js
- webapp/core/facade/Project.js
- webapp/public/javascripts/angular/data-provider/controllers/registration.js
- webapp/public/javascripts/angular/data-provider/directives.js
- webapp/public/javascripts/angular/status/status.js
- webapp/views/configuration/provider.html
Fixing url from the table status;
Adding Data Server Registration improvements.
@raphaelrpl 
**Type:**
**Platform:**
> Adding improvements and bug fixes

- webapp/public/javascripts/angular/interpolator/controllers/interpolator-register-update.js
Fix time unit on combobox for Interpolator
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix time unit on combobox for Interpolator
</details>
> Fix time unit on combobox for Interpolator

- webapp/core/FileRequest.js
- webapp/public/javascripts/angular/data-provider/controllers/registration.js
- webapp/public/javascripts/angular/data-provider/directives.js
- webapp/views/configuration/provider.html
Listing the paths that was added in defaultFilePathList;
Validating if the path variable is empty.
@raphaelrpl
**Type:**
**Platform:**
> Listing the paths that was added in defaultFilePathList.

- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/data-series/templates/csvFieldDetail.html
Set default values in CSV importation
**Type:**
**Platform:**
<details>
*Enhancement:*
* Set default values in CSV importation
</details>
> Minor change: Set default values in CSV Data Series

- webapp/public/javascripts/angular/status/status.js
Identifying type of service.
@raphaelrpl
**Type:**
**Platform:**
> Fixing link.

- webapp/controllers/configuration/ImportStaticFiles.js
- webapp/core/ShapeImporter.js
- webapp/public/javascripts/angular/data-series/directives.js
Fix shape upload. We are incremeting size of stdout buffer to avoid upload crash. It is important since shp2pgsql may display info or warning
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix shape upload. We are incremeting size of stdout buffer to avoid upload crash
</details>
> Fix shape upload. We are incremeting stdout buffer to avoid upload crash

- src/terrama2/impl/DataAccessorGrADS.cpp
- src/terrama2/services/appserver/main.cpp
Fix collector file removing for GrADS
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix collector file removing for GrADS
</details>
> Fix collector file removing for GrADS

- build/cmake/CMakeLists.txt
> Update to 4.0.9

- src/terrama2/core/data-model/Filter.hpp
- src/terrama2/core/utility/FilterUtils.cpp
- src/terrama2/impl/DataAccessorFile.cpp
- src/terrama2/services/analysis/core/GridContext.cpp
- src/terrama2/services/analysis/core/GridContext.hpp
- src/terrama2/services/analysis/core/Service.cpp
- src/terrama2/services/analysis/core/grid/Operator.cpp
Fix reprocessing historical data time interval
**Reviewers**:
@rosamariakato 
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix reprocessing historical data time interval
</details>
> Fix reprocessing historical data time interval

- src/terrama2/core/data-model/Filter.hpp
- src/terrama2/core/utility/FilterUtils.cpp
- src/terrama2/impl/DataAccessorGrADS.cpp
- src/terrama2/services/analysis/core/GridContext.cpp
- src/terrama2/services/analysis/core/grid/Operator.cpp
- webapp/config/sample_instances/default.json
- webapp/public/javascripts/angular/datetimepicker/directive.js
Fix grid analysis reprocessing
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix grid analysis reprocessing
</details>
> Fix grid analysis reprocessing

- share/terrama2/semantics/geo-obj-postgis.json
- src/terrama2/impl/DataAccessorStaticDataViewPostGIS.cpp
- src/terrama2/impl/DataAccessorStaticDataViewPostGIS.hpp
- src/terrama2/impl/Utils.cpp
- src/terrama2/services/view/core/data-access/Geoserver.cpp
- webapp/controllers/api/DataSeries.js
- webapp/core/Exportation.js
- webapp/core/PostgisRequest.js
- webapp/core/ShapeImporter.js
- webapp/core/utility/connection.js
- webapp/core/utility/createView.js
- webapp/package.json
- webapp/public/javascripts/angular/advanced.html
- webapp/public/javascripts/angular/data-series/controllers.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/data-series/services.js
- webapp/public/javascripts/angular/wizard.html
- webapp/routes/api/DataSeries.js
- webapp/tests/core/ShapeImporter.spec.js
- webapp/tests/core/utility/connection.spec.js
- webapp/tests/core/utility/createView.spec.js
- webapp/tests/core/utility/mocks/connection.js
- webapp/tests/core/utility/mocks/createView.js
This PR solves the problem with Filtered Tables (View concept) on Static Data Series. It also includes unittest for these modules.
**Type:**
**Platform:**
<details>
*Enhancement:*
* Filtered Tables (View) and unittest
</details>
> Filtered Tables (View) and unittest

- webapp/controllers/api/DataSeries.js
- webapp/core/DataManager.js
- webapp/core/ShapeImporter.js
- webapp/core/data-model/DataSeries.js
- webapp/core/facade/Collector.js
- webapp/tests/core/ShapeImporter.spec.js
This PR solves the DCP update and force schema to public while uploading shapefile.
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix DCP update - Add/Remove dataset in Dynamic DataSeries DCP
* Force schema to public while upload shapefile in Static DataSeries page
</details>
> Major fixes: DCP update and schema - public

- src/terrama2/impl/DataAccessorFile.cpp
Fix duplicate file data in collector
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix duplicate file data in collector
</details>
> Fix duplicate file in collector

- webapp/public/stylesheets/terrama2.css
- webmonitor/public/stylesheets/TerraMA2WebMonitor.css
- webmonitor/views/index.html
Fixed layout problems
@raphaelrpl 
**Type:**
**Platform:**
> Fixed layout problems

- share/terrama2/scripts/parse-http-server-html.py
Fix HTTP collector
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix HTTP collector
</details>
> Fix HTTP collector

- src/terrama2/core/utility/Utils.cpp
- src/terrama2/core/utility/Utils.hpp
- src/terrama2/impl/DataAccessorDcpInpe.cpp
- src/terrama2/impl/DataAccessorDcpInpe.hpp
- src/terrama2/impl/DataRetrieverFTP.cpp
- src/terrama2/services/analysis/core/grid/Operator.cpp
- src/terrama2/services/view/core/Utils.cpp
- src/terrama2/services/view/core/Utils.hpp
- src/terrama2/services/view/core/data-access/Geoserver.cpp
- webapp/core/FtpRequest.js
- webapp/core/utility/ftp.js
- webapp/package.json
The terrama2 application is not working with FTP active mode validation and data collection. This patch aims to solve this problem.
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix FTP active mode
</details>
> Fix FTP active mode

- src/examples/core/BitsetPolygon.cpp
- src/terrama2/core/utility/BitsetIntersection.cpp
- src/terrama2/core/utility/BitsetIntersection.hpp
- src/terrama2/core/utility/Utils.hpp
- src/terrama2/impl/DataAccessorFile.cpp
- src/terrama2/services/analysis/core/grid/zonal/Operator.cpp
- src/terrama2/services/analysis/core/grid/zonal/Utils.hpp
- src/terrama2/services/analysis/core/grid/zonal/forecast/Operator.cpp
- src/terrama2/services/analysis/core/grid/zonal/forecast/accum/Operator.cpp
Fix image crop in collector
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix image crop in collector 
</details>
> Fix image crop in collector 

- src/terrama2/core/utility/Service.hpp
- src/terrama2/services/analysis/core/Service.cpp
- src/terrama2/services/analysis/core/Service.hpp
- webapp/public/javascripts/angular/analysis/controllers/register-update.js
- webapp/public/javascripts/angular/data-series/schedule.js
- webapp/public/javascripts/angular/data-series/templates/schedule.html
Fix reprocessing historical data by filename
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix reprocessing historical data by filename
</details>
> Fix reprocessing historical data by filename

- webapp/core/facade/DataProvider.js
Fix Data provider update properties on WebApp
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix Data provider update properties on WebApp
</details>
> Fix Data provider update properties on WebApp

- Changelog.md
- LINUX.md
- helper/Plataforma de Monitoramento Ambiental TerraMA².html
- helper/Plataforma de Monitoramento Ambiental TerraMAý.html
- helper/introduction.html
- packages/debian-package/deb-gtest.sh
- packages/debian-package/deb-helper.sh
- src/examples/core/BitsetPolygon.cpp
- src/examples/core/ReadCemadenData.cpp
- src/terrama2/core/utility/BitsetIntersection.cpp
- src/terrama2/core/utility/BitsetIntersection.hpp
- src/terrama2/core/utility/Utils.hpp
- src/terrama2/impl/DataAccessorFile.cpp
- src/terrama2/services/analysis/core/grid/zonal/Operator.cpp
- src/terrama2/services/analysis/core/grid/zonal/Utils.hpp
- src/terrama2/services/analysis/core/grid/zonal/forecast/Operator.cpp
- src/terrama2/services/analysis/core/grid/zonal/forecast/accum/Operator.cpp
- webapp/config/sample_instances/default.json
- webapp/core/Application.js
- webapp/locales/en_US.json
- webapp/locales/es_ES.json
- webapp/locales/pt_BR.json
- webapp/package.json
- webmonitor/locales/en.json
- webmonitor/locales/es.json
- webmonitor/locales/pt.json
- webmonitor/package.json
Revert commit - Performance issues on specific rasters
**Type:**
**Platform:**
<details>
*Bug fix:*
* Revert commit - Performance issues on specific rasters
</details>
> Revert commit - Performance issues on specific rasters

- src/terrama2/services/analysis/core/grid/Operator.cpp
- src/terrama2/services/analysis/core/grid/Operator.hpp
- src/terrama2/services/analysis/core/grid/forecast/Operator.cpp
- src/terrama2/services/analysis/core/grid/history/Operator.cpp
- src/terrama2/services/analysis/core/utility/JSonUtils.cpp
Fix interpolation dummy on Analysis GRID
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix interpolation dummy on Analysis GRID
</details>
> Fix interpolation dummy on Analysis GRID

- webapp/controllers/api/DataSeries.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/data-series/services.js
- webapp/public/javascripts/angular/wizard.html
Validating view registration.
@raphaelrpl 
**Type:**
**Platform:**
> Validating view registration.

- webapp/public/javascripts/angular/analysis/components/vectorProcessing.js
- webapp/public/javascripts/angular/wizard.html
This PR closes #1699 which the attribute was not listing.
**Type:**
**Platform:**
<details>
*Bug fix:*
* Close #1699 - Fix attribute listing on Analysis
</details>
> Close #1699 - Fix attribute listing on Analysis

- src/terrama2/services/view/core/data-access/Geoserver.cpp
- webapp/migrations/20190604000000-allow-null-view-automatic-schedule.js
- webapp/public/javascripts/angular/analysis/app.js
- webapp/public/javascripts/angular/analysis/components/queryBuilder.js
- webapp/public/javascripts/angular/analysis/components/queryBuilderWrapper.js
- webapp/public/javascripts/angular/analysis/components/vectorProcessing.js
- webapp/public/javascripts/angular/analysis/data/query-operators.json
- webapp/public/javascripts/angular/analysis/directives.js
- webapp/public/javascripts/angular/collapser/directives.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/schema-form-plugin/querybuilder/controller.js
- webapp/public/javascripts/angular/schema-form-plugin/querybuilder/module.js
- webapp/views/configuration/analysis.html
Close #1701 - Fix query build operators 
**Type:**
**Platform:**
<details>
*Enhancement:*
* Review Query build operators  #1701 
</details>
> Fix query build operators

- src/terrama2/core/interpreter/PythonInterpreter.cpp
Removing cout.
@raphaelrpl 
**Type:**
**Platform:**
> Removing cout.

- webapp/package-lock.json
- webapp/package.json
- webapp/public/javascripts/angular/status/status.js
Erased test line on status component
**Type:**
**Platform:**
> Erased test line on status component

- webapp/public/javascripts/angular/analysis/components/vectorProcessing.js
Refactory the vector processing component.
**Type:**
**Platform:**
> Refactory the vector processing component.

- src/terrama2/services/view/core/data-access/Geoserver.cpp
- src/terrama2/services/view/core/vectorial-processing/Utils.cpp
Fixing the way to show layers from vector processing operation.
@juan0101 
**Type:**
**Platform:**
> Fixing the way to show layers from vector processing operation.

- webapp/config/db.json
- webapp/controllers/api/report.js
- webapp/public/javascripts/angular/analysis/components/vectorProcessing.js
- webapp/routes/api/report.js
- webmonitor/public/javascripts/components/Calendar.js
- webmonitor/public/javascripts/components/Charts.js
- webmonitor/public/stylesheets/TerraMA2WebMonitor.css
Fixed layout bugs on webmonitor and changes on report to adapt with the report app
**Type:**
**Platform:**
> Layout bugs and changes on report

- webapp/public/javascripts/angular/analysis/components/vectorProcessing.js
Fixing the way to get attributes name from layer.
@juan0101
**Type:**
**Platform:**
> Fixing the way to get attributes name from layer.

- share/terrama2/scripts/sql-functions/vectorial_processing_intersection.sql
- webapp/public/javascripts/angular/analysis/components/vectorProcessing.js
Fixing the way to get table name from vector processing layer.
Adding projection to output layer from vector processing.
@juan0101
**Type:**
**Platform:**
> Fixing the way to get table name from vector processing layer and Adding projection to output layer.

- share/terrama2/scripts/sql-functions/vectorial_processing_intersection.sql
- webapp/core/facade/tcp-manager/ProcessFinished.js
- webapp/public/javascripts/angular/analysis/components/vectorProcessing.js
* Reverting alterations on listConditionedProcess function;
* Validating input attributes from dynamic and static layers;
* Adding vector processing component improvements.
@juan0101
**Type:**
**Platform:**
> Adding Adjustaments

- webapp/public/javascripts/angular/wizard.html
Hide Attributes head
**Type:**
**Platform:**
> Hide Attributes head

- webapp/public/javascripts/angular/analysis/components/vectorProcessing.js
Fixing the way to remove attributes when another layer is selected.
@juan0101 
**Type:**
**Platform:**
> Fixing the way to remove attributes when another layer is selected.

- webapp/controllers/api/report.js
Fixed select of the getAnalysisData on report
**Type:**
**Platform:**
> Fixed select of the getAnalysisData on report

- webapp/controllers/configuration/StaticDataSeries.js
- webapp/core/Utils.js
- webmonitor/controllers/GetAttributesTableController.js
- webmonitor/public/javascripts/TerraMA2WebMonitor.js
Possibility for add GEOM collumn on table info in monitor
**Type:**
**Platform:**
> Possibility for add GEOM collumn on table info in monitor

- webapp/config/db.json.example
- webapp/controllers/api/report.js
- webapp/package-lock.json
Fix date in methods 
**Type:**
**Platform:**
> fix bug in date

- src/terrama2/services/view/core/data-access/Geoserver.cpp
* Adding calendar in layers from vector processing.
@juan0101
**Type:**
**Platform:**
> Adding calendar in layers from vector processing.

- packages/debian-package/deb-terrama2.sh
- packages/debian-package/terrama2.conf.cmake
* Updating terralib version on cmake.
@juan0101 
**Type:**
**Platform:**
> Updating terralib version on cmake.

- packages/debian-package/deb-terrama2.sh
- packages/debian-package/terrama2.conf.cmake
Reverts TerraMA2/terrama2#1733
> Revert "Updating terralib version on cmake."

- src/terrama2/services/view/core/data-access/Geoserver.cpp
- src/terrama2/services/view/core/vectorial-processing/Utils.cpp
- src/terrama2/services/view/core/vectorial-processing/Utils.hpp
* Fixing column attributes from vector processing layer.
@juan0101
**Type:**
**Platform:**
> Fixing column attributes from vector processing layer.

- webmonitor/controllers/GetAttributesTableController.js
- webmonitor/public/javascripts/TerraMA2WebMonitor.js
- webmonitor/public/javascripts/components/AttributesTable.js
Fix bugs on table information
@MarceloPilatti @hrgomesvieira 
**Type:**
**Platform:**
> Fix bugs on table information

- src/terrama2/services/view/core/data-access/Geoserver.cpp
* Fixing calendar from vector processing layers.
@juan0101 
**Type:**
**Platform:**
> Fixing calendar from vector processing layers.

- webapp/controllers/api/report.js
Minor fixes on report
**Type:**
**Platform:**
> Minor fixes on report

- src/terrama2/services/view/core/data-access/Geoserver.cpp
* Fixing build geometry style from vector processing.
@juan0101 
**Type:**
**Platform:**
> Fixing build geometry style from vector processing.

- webapp/controllers/api/City.js
- webapp/controllers/api/report.js
- webapp/routes/api/City.js
- webmonitor/public/stylesheets/TerraMA2WebMonitor.css
- webmonitor/views/index.html
Added cities route
**Type:**
**Platform:**
> City route

- share/terrama2/scripts/sql-functions/vectorial_processing_intersection.sql
* Fixing the way to calc area in hectare. Casting geom to geography.
@juan0101 
**Type:**
**Platform:**
> Fixing the way to calc area in hectare. Casting geom to geography.

- webmonitor/public/stylesheets/TerraMA2WebMonitor.css
Fixed project arrow position
**Type:**
**Platform:**
> Fixed project arrow position

- share/terrama2/scripts/sql-functions/vectorial_processing_intersection.sql
* Fixing updating table.
@juan0101 
**Type:**
**Platform:**
> Fixing updating table.

- src/terrama2/services/analysis/core/AnalysisExecutor.cpp
* Fixing vector processing operation status.
@juan0101 
**Type:**
**Platform:**
> Fixing vector processing operation status.

- webapp/controllers/api/report.js
- webapp/routes/api/report.js
service created to return dashboard totals
**Type:**
**Platform:**
> service created to return dashboard totals

- webapp/controllers/api/Car.js
- webapp/controllers/api/report.js
Changes on the SQL of the report controller
**Type:**
**Platform:**
> Changes on the report controller

- webapp/controllers/api/Car.js
- webapp/controllers/api/report.js
Changes on sql report
**Type:**
**Platform:**
> Report changes

- webapp/public/javascripts/angular/analysis/components/vectorProcessing.js
automation class name selection in vector processing
**Type:**
**Platform:**
> automation class name selection in vector processing

- webmonitor/views/index.html
fix css bug in Attributes Table
**Type:**
**Platform:**
> fix css bug in Attributes Table

- webmonitor/controllers/GetAttributesTableController.js
Fix Bug (Number of collumns are equal but not the same) on table info.
**Type:**
**Platform:**
> Fix Bug (Number of collumns are equal but not the same) on table info

- webmonitor/controllers/GetAttributesTableController.js
Fix bug (eliminate continue from forEach)
**Type:**
**Platform:**
> Fix bug (eliminate continue from forEach)

- webapp/migrations/20191108000000-change-analysis-metadata-value-type.js
change analysis metadata value column
**Type:**
**Platform:**
> change analysis metadata value column

- webapp/controllers/api/Car.js
Changes on the car report sql
@hrgomesvieira @juan0101 
**Type:**
**Platform:**
> Changes on the car report sql

- webapp/controllers/api/Biome.js
- webapp/controllers/api/City.js
- webapp/controllers/api/ConsolidatedUseArea.js
- webapp/controllers/api/IndigenousLand.js
- webapp/controllers/api/report.js
- webapp/package-lock.json
- webapp/routes/api/City.js
- webapp/routes/api/ConsolidatedUseArea.js
- webapp/routes/api/IndigenousLand.js
Created services for filling the theme filter combos and fix sqls.
**Type:**
**Platform:**
> Created services

- webapp/controllers/api/Car.js
- webapp/routes/api/Car.js
created service to search car by cpf
**Type:**
**Platform:**
> B4.1.0 - created service to search car by cpf

- webapp/controllers/api/Projus.js
- webapp/core/facade/Filter.js
- webapp/routes/api/Projus.js
Dashboard Ok
**Type:**
**Platform:**
> Dashboard Ok

- webapp/controllers/api/Car.js
- webapp/controllers/api/report.js
- webapp/core/facade/Filter.js
- webapp/core/facade/ReportService.js
Created method findAnaliseData, create filter in method getAnalysisData. Code Refactored in methods and class.
**Type:**
**Platform:**
> B4.1.0 - Filter

- webapp/controllers/api/Car.js
- webapp/controllers/api/report.js
Changed report table sql
**Type:**
**Platform:**
> Changed report table sql

- webapp/controllers/api/report.js
- webapp/core/facade/Filter.js
- webapp/core/facade/ReportService.js
fixed seach static data
**Type:**
**Platform:**
> B4.1.0 fixed seach static data

- webapp/core/facade/Filter.js
Modifications in queries of the filter
**Type:**
**Platform:**
> Modifications in queries of the filter

- webapp/controllers/api/Car.js
- webapp/controllers/api/report.js
Changed viewId param to view on the report controller
**Type:**
**Platform:**
> Changed viewId param to view on the report controller

- src/terrama2/impl/DataAccessorWFS.cpp
- src/terrama2/impl/DataRetrieverWFS.cpp
* Adding ajustments
@juan0101 
**Type:**
**Platform:**
> Adding ajustments

- webapp/core/facade/Filter.js
- webapp/core/facade/View.js
Fixed create view and implemented filter for cpfCnpj
**Type:**
**Platform:**
> Fixed create view and implemented filter for cpfCnpj

- build/cmake/terrama2-cpack-options.cmake.in
- packages/debian-package/deb-terrama2.sh
- packages/debian-package/terrama2.conf.cmake
- share/terrama2/scripts/sql-functions/vectorial_processing_intersection.sql
- src/terrama2/services/analysis/core/vector-processing/Intersection.cpp
- webapp/core/TcpManager.js
- webapp/core/Utils.js
- webapp/core/facade/DataProvider.js
- webapp/core/facade/tcp-manager/ProcessFinished.js
- webapp/package.json
- webapp/public/javascripts/angular/analysis/components/vectorProcessing.js
Fix vector processing utilities
@juan0101, @MarceloPilatti 
**Type:**
**Platform:**
<details>
*New feature:*
* Item one
* Sub item one
*Enhancement:*
* Item one
* Sub item one
*Bug fix:*
* Item one
* Sub item one
</details>
> Fix vector processing utilities

- webapp/controllers/api/Car.js
- webapp/controllers/api/report.js
- webapp/core/facade/Filter.js
Updated views of deter views
**Type:**
**Platform:**
> Updated views of deter views

- src/terrama2/services/view/core/Utils.cpp
@
**Type:**
**Platform:**
<details>
*New feature:*
* Item one
* Sub item one
*Enhancement:*
* Item one
* Sub item one
*Bug fix:*
* Item one
* Sub item one
</details>
> Fix line stroke dash

- webapp/controllers/api/report.js
- webapp/core/facade/ReportService.js
Update tables and views PRODES and DETER
**Type:**
**Platform:**
> Update tables and views

- .gitignore
- webapp/config/db.json.example
- webapp/controllers/api/Car.js
- webapp/controllers/api/report.js
Changes on the report sql
**Type:**
**Platform:**
> Changes on the report sql

- webapp/controllers/api/report.js
Changes on the report
**Type:**
**Platform:**
> Changes on the report

- webapp/core/facade/Filter.js
Change in method dashboard totals values for data the AQ
**Type:**
**Platform:**
> Change in method dashboard totals values for data the AQ

- webapp/controllers/api/report.js
- webapp/core/facade/ReportService.js
fixed params of the filter in table of the maps
**Type:**
**Platform:**
> fixed params of the filter in table of the maps

- webapp/config/settings.json
Settings in localhost
**Type:**
**Platform:**
> Settings in localhost

- webapp/controllers/api/report.js
Update table name and field name in report.js
**Type:**
**Platform:**
> Update table name and field name in report.js

- webapp/core/facade/Filter.js
Fixed error in view not created in geoserver
**Type:**
**Platform:**
> Fixed error in view not created in geoserver

- webapp/core/facade/Filter.js
Fixed err in layers no created. Exception handling
**Type:**
**Platform:**
> Fixed err in layers no created. Exception handling

- src/terrama2/impl/DataAccessorFile.cpp
- src/terrama2/impl/DataAccessorFile.hpp
- src/terrama2/impl/DataAccessorGeometricObjectOGR.cpp
- src/terrama2/impl/DataAccessorGeometricObjectOGR.hpp
- src/terrama2/services/alert/core/AlertExecutor.cpp
- src/terrama2/services/analysis/core/MonitoredObjectContext.cpp
- src/terrama2/services/view/core/data-access/DataAccess.cpp
- src/terrama2/services/view/core/data-access/Geoserver.cpp
Fix:
- Collector OGR problem
- Identifier Monitored Object
- Attach Image in email
@MarceloPilatti @raphaelrpl 
**Type:**
**Platform:**
> Fiz Collector OGR, identifier and attach Image

- webapp/controllers/api/report.js
Added burned areas on the report
**Type:**
**Platform:**
> Added burned areas on the report

- webapp/controllers/api/report.js
Fixed sql table names on the report
**Type:**
**Platform:**
> Fixed sql table names on the report

- src/terrama2/impl/DataAccessorFile.cpp
- src/terrama2/services/view/core/data-access/Geoserver.cpp
Fix TIFF fid bug and get ZIP file from FTP
**Type:**
**Platform:**
> Fix TIFF fid bug and get ZIP file from FTP

- webapp/core/facade/Filter.js
Fixed bug in at the Filter.js, facade
**Type:**
**Platform:**
> Fixed bug in at the Filter.js, facade

- webapp/controllers/api/Biome.js
- webapp/controllers/api/Car.js
- webapp/controllers/api/ConservationUnit.js
- webapp/controllers/api/Dashboard.js
- webapp/controllers/api/IndigenousLand.js
- webapp/controllers/api/Projus.js
- webapp/controllers/api/report.js
- webapp/core/facade/Filter.js
- webapp/core/facade/ReportService.js
> Fixed bug in filter by CarFederal

- webapp/controllers/api/Car.js
Fixed Bug in table find
**Type:**
**Platform:**
> Fixed Bug in table find

- webapp/controllers/api/report.js
Fixed missing bracket on report
**Type:**
**Platform:**
> Fixed missing bracket on report

- webapp/core/facade/tcp-manager/ProcessFinished.js
Fix Proccess Dispatcher
**Type:**
**Platform:**
> Fix Proccess Dispatcher

- webapp/controllers/api/report.js
Fixed layers ids on the report
@
**Type:**
**Platform:**
> Fixed layers ids on the report

- webapp/controllers/api/report.js
Fixed value is null
**Type:**
**Platform:**
> Fixed value is null

- webapp/controllers/api/report.js
Change 'area'
**Type:**
**Platform:**
> Change 'area'

- webapp/controllers/api/report.js
- webapp/package-lock.json
Fixed a bug on the report detailed vision
**Type:**
**Platform:**
> Fixed a bug on the report detailed vision

- webapp/controllers/api/report.js
Added sqls for new the new data for the report
**Type:**
**Platform:**
> Added sqls for new the new data for the report

- share/terrama2/scripts/sql-functions/vectorial_processing_intersection.sql
- src/terrama2/services/alert/core/AlertExecutor.cpp
- src/terrama2/services/alert/core/Report.cpp
Fix Vector Process put null in automatic schedule
Fix verification and when to send alert email
**Type:**
**Platform:**
> Fix automatic schedule table and send alert email

- webapp/core/facade/Filter.js
dynamic configuration alerts and optimization performance
**Type:**
**Platform:**
> dynamic config alerts

- webapp/controllers/api/report.js
- webapp/core/facade/ReportService.js
- webapp/package-lock.json
Change methods for implementation of the dynamic view
**Type:**
**Platform:**
> Change methods for implementation of the dynamic view

- webapp/controllers/api/report.js
- webmonitor/public/javascripts/TerraMA2WebMonitor.js
- webmonitor/public/stylesheets/TerraMA2WebMonitor.css
- Fixed auto update map refresh
- Fixed info tool and about size, legend box position and 
@juan0101 
**Type:**
**Platform:**
> Fixed dialog position and size

- webmonitor/public/javascripts/TerraMA2WebMonitor.js
Filter static data field GID on table info
@MarceloPilatti @juan0101 
**Type:**
**Platform:**
> Filter static data field GID on table info

- package-lock.json
- webapp/package.json
- webmonitor/gruntfile.js
- webmonitor/public/stylesheets/TerraMA2WebMonitor.css
Fixed height of the dialog on monitor
@juan0101 
**Type:**
**Platform:**
> Fixed height of the dialog on monitor

- src/terrama2/impl/DataAccessorFile.cpp
Fiz dont Filter CSV File
**Type:**
**Platform:**
> Fiz dont Filter CSV File

- webapp/controllers/api/Dashboard.js
Set first analysis with exibition area
**Type:**
**Platform:**
> Set first analysis with exibition area

- webapp/package.json
- webmonitor/package.json
Removed grunt from npm start command
@juan0101 
**Type:**
**Platform:**
> Removed grunt from npm start command

- webapp/core/Application.js
Create settings.json and db.json if not exists
**Type:**
**Platform:**
> Create settings.json and db.json if not exists

- src/terrama2/services/collector/core/Service.cpp
Fix Status color when get data from File with filter
**Type:**
**Platform:**
> Fix Status color when get data from File with filter

- src/terrama2/services/analysis/core/grid/zonal/forecast/accum/Operator.cpp
Fix down analysis service when read last band of tiff file
**Type:**
**Platform:**
> Fix down analysis service when read last band of tiff file

- share/terrama2/scripts/sql-functions/vectorial_processing_intersection.sql
- webapp/public/javascripts/angular/analysis/components/vectorProcessing.js
- webapp/public/javascripts/angular/analysis/controllers/register-update.js
bug fix on add filters by attributes[Analysis]
@juan0101  @MarceloPilatti
**Type:**
**Platform:**
> Bug fix on filter by attributes[Analysis]

- webapp/public/javascripts/angular/views/controllers/view-register-update.js
- webapp/public/javascripts/angular/views/templates/style.html
Adding Style for Vector Processing View
**Type:**
**Platform:**
> Adding Style for Vector Processing View

- webapp/controllers/api/Car.js
ADD atribute has_pdf
**Type:**
**Platform:**
> ADD Attibute has_pdf

- webapp/package.json
Removed grunt from npm start
@juan0101 
**Type:**
**Platform:**
> Removed grunt from npm start

- scripts/postinst.in
Changed yarn for npm on postinst.sh
@juan0101 
**Type:**
**Platform:**
> Changed yarn for npm on postinst.sh

- webapp/public/javascripts/angular/analysis/components/vectorProcessing.js
- webapp/public/javascripts/angular/analysis/controllers/register-update.js
bug fix on create analysis of object monitored
**Type:**
**Platform:**
> bug fix on create analysis of object monitored

- webapp/controllers/api/vectorial_processing_intersection.sql
sql file for creation of new database connection
**Type:**
**Platform:**
> sql file for creation of new database connection

- webapp/controllers/api/Uri.js
bug fix on creation of new database
**Type:**
**Platform:**
> bug fix on creation of new database

- webapp/public/javascripts/angular/analysis/components/vectorProcessing.js
bug fixing in the construction and editing of vector analysis v.1
**Type:**
**Platform:**
> bug fixing in the construction and editing of vector analysis v.1

- webapp/locales/en_US.json
- webapp/locales/pt_BR.json
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/wizard.html
bug fix on name of checkboxes and on list of tables in the select tag
**Type:**
**Platform:**
> bug fix on name of checboxes and on list of tables in the select tag

- webapp/locales/en_US.json
- webapp/locales/pt_BR.json
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/wizard.html
Reverts TerraMA2/terrama2#1847
> Revert "bug fix on name of checboxes and on list of tables in the select tag"

- webapp/public/javascripts/angular/analysis/components/vectorProcessing.js
Reverts TerraMA2/terrama2#1846
> Revert "bug fixing in the construction and editing of vector analysis v.1"

- webapp/controllers/api/Uri.js
Reverts TerraMA2/terrama2#1844
> Revert "bug fix on creation of new database"

- webapp/views/configuration/analysis.html
return DCP select box in new Analysis
**Type:**
**Platform:**
> return DCP select box in new Analysis

- src/terrama2/services/alert/core/Alert.hpp
- src/terrama2/services/alert/core/Report.cpp
- src/terrama2/services/alert/core/Utils.cpp
- src/terrama2/services/alert/impl/Utils.cpp
changes in Alert email
**Type:**
**Platform:**
> changes in Alert email

- src/terrama2/services/alert/core/Report.cpp
Change arrow from Report email
**Type:**
**Platform:**
> Change arrow from Report email

- src/terrama2/services/alert/core/Utils.cpp
insert span to html alert email
**Type:**
**Platform:**
> insert span to html alert email

- src/terrama2/services/alert/core/Utils.cpp
adding html escape in alert email
@MarceloPilatti  @MiguelThiagoAlvarenga 
**Type:**
**Platform:**
> adding html escape in alert email

- webmonitor/public/javascripts/TerraMA2WebMonitor.js
- webmonitor/public/stylesheets/TerraMA2WebMonitor.css
- webmonitor/views/index.html
Changed info tool size
@juan0101 
**Type:**
**Platform:**
<details>
*New feature:*
* Item one
* Sub item one
*Enhancement:*
* Item one
* Sub item one
*Bug fix:*
* Item one
* Sub item one
</details>
> Changed info tool size

- src/terrama2/services/alert/core/Report.cpp
- src/terrama2/services/alert/core/Utils.cpp
Change arrows to show in outlook - alert email
**Type:**
**Platform:**
> Change arrows to show in outlook - alert email

- webapp/public/javascripts/angular/advanced.html
- webapp/public/javascripts/angular/analysis/components/vectorProcessing.js
- webmonitor/public/javascripts/TerraMA2WebMonitor.js
Fixed info tool not showing error
@juan0101 
**Type:**
**Platform:**
> Fixed info tool not showing error

- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/wizard.html
bug fix on checkboxes when change to advanced mode
@juan0101 @MarceloPilatti 
**Type:**
> bug fix on checkboxes when change to advanced mode

- src/terrama2/services/analysis/core/AnalysisExecutor.cpp
- webapp/core/Enums.js
- webapp/core/PostgisRequest.js
- webapp/core/facade/Analysis.js
- webapp/public/javascripts/angular/analysis/components/vectorProcessing.js
- webapp/public/javascripts/angular/analysis/controllers/register-update.js
bug correction in the creation and validation of vector analysis
**Type:**
> bug correction in the creation and validation of vector analysis

- webcomponents/javascripts/src/components/MapDisplay.TerraMA2WebComponents.js
- webmonitor/config/sample_instances/user_conf.json
- webmonitor/config/sample_instances/user_conf.json.example
- webmonitor/config/sample_instances/user_conf.md
- webmonitor/core/Application.js
- webmonitor/gruntfile.js
- webmonitor/public/javascripts/TerraMA2WebMonitor.js
- webmonitor/public/javascripts/components/MapTools.js
- webmonitor/public/javascripts/components/State.js
- webmonitor/routes/index.js
- webmonitor/views/index.html
Created json to configure some preferences on the webmonitor
@juan0101 
**Type:**
**Platform:**
> Created json to configure some preferences on the webmonitor

- install/terrama2-ubuntu-16-04-config.sh
- webmonitor/config/sample_instances/user_conf.md
Added TerraMA build script
@juan0101 
**Type:**
**Platform:**
> Added TerraMA build script

- webcomponents/javascripts/src/components/MapDisplay.TerraMA2WebComponents.js
- webmonitor/config/sample_instances/user_conf.md
- webmonitor/public/javascripts/TerraMA2WebMonitor.js
- webmonitor/public/stylesheets/TerraMA2WebMonitor.css
- webmonitor/views/index.html
Removed logo text when user_conf changes the logo and added attributions to the map
@juan0101 
**Type:**
**Platform:**
> Removed logo text when user_conf changes the logo and added attributions to the map

- webmonitor/public/javascripts/TerraMA2WebMonitor.js
Default project from user_conf.json added to initial request
@juan0101 
**Type:**
**Platform:**
> Default project from user_conf.json added to initial request

- webapp/public/javascripts/angular/data-provider/directives.js
- webapp/public/javascripts/angular/schema-form-plugin/mask-warn/directives/terrama2-mask-field.js
bug fix in building form schema
@juan0101 @MarceloPilatti 
**Type:**
**Platform:**
> bug fix in building form schema

- scripts/mac/postinst.sh
- scripts/postinst.in
- scripts/prerm.in
- scripts/remove-config.py
Removed instances folder creation from webapp postinst.sh configuration and added the settings.sjon
@juan0101 
**Type:**
**Platform:**
> Fixes on the postinst.sh

- scripts/postinst.in
Fixed postinst script webapp configuration db.json file
@juan0101 
**Type:**
**Platform:**
> Fixed postinst script webapp configuration db.json file

- webmonitor/public/javascripts/TerraMA2WebMonitor.js
Fixed info tool error on raster data
@juan0101 
**Type:**
**Platform:**
> Fixed info tool error on raster data

- webapp/config/settings.json.example
- webapp/seeders/20190501115200-service-instance-view.js
Added geoserver host, port and base path configuration to the settings.json.
@juan0101 
**Type:**
**Platform:**
> Added geoserver configuration to the settings.json

- webmonitor/public/javascripts/TerraMA2WebMonitor.js
Fixed bug on the default language of the monitor
@juan0101
**Type:**
**Platform:**
> Fixed bug on the default language of the monitor

- webapp/views/login.html
ajusdment on login screen
@juan0101 @MarceloPilatti 
**Type:**
**Platform:**
> ajusdment on login screen

- webapp/controllers/api/AttributesTable.js
- webapp/public/javascripts/angular/data-series/registration.js
bug fix in the attributes tab
**Type:**
**Platform:**
> bug fix in the attributes tab

- webapp/public/javascripts/angular/data-series/registration.js
bug fix in the attributes tab - reset attributes
**Type:**
* Item one
* Sub item one
*Bug fix:*
* Item one
* Sub item one
</details>
> bug fix in the attributes tab - reset attributes

- webapp/controllers/api/AttributesTable.js
Fixed bugs on the info tool for grid layers
@juan0101 
**Type:**
**Platform:**
> Fixed bugs on the info tool for grid layers

- webapp/controllers/api/AttributesTable.js
- webapp/public/javascripts/angular/data-series/registration.js
bug fix on tab attributes(static data)
@juan0101 @MarceloPilatti 
**Type:**
**Platform:**
> bug fix on tab attributes(static data)

- src/terrama2/core/data-model/Filter.hpp
- src/terrama2/core/utility/FilterUtils.cpp
- src/terrama2/core/utility/Service.cpp
- src/terrama2/services/collector/core/Service.cpp
Fix verify compare dates in collector
**Type:**
**Platform:**
> Fix verify compare dates in collector

- webapp/public/javascripts/angular/analysis/controllers/register-update.js
Fix Frenquency start time
**Type:**
**Platform:**
> Fix Frenquency start time

- src/terrama2/core/utility/FilterUtils.cpp
- src/terrama2/core/utility/Service.cpp
- src/terrama2/core/utility/TimeUtils.cpp
- src/terrama2/core/utility/TimeUtils.hpp
- webapp/locales/pt_BR.json
- webapp/public/javascripts/angular/data-series/registration.js
Fix Filter bug
**Type:**
**Platform:**
>  Fix Filter bug

- webapp/public/javascripts/angular/analysis/controllers/register-update.js
Reverts TerraMA2/terrama2#1899
> Revert "Fix Frenquency start time"

- src/terrama2/core/utility/FilterUtils.cpp
- src/terrama2/core/utility/Service.cpp
- src/terrama2/core/utility/TimeUtils.cpp
- src/terrama2/core/utility/TimeUtils.hpp
- webapp/locales/pt_BR.json
- webapp/public/javascripts/angular/data-series/registration.js
Reverts TerraMA2/terrama2#1900
> Revert " Fix Filter bug"

- src/terrama2/core/data-model/Filter.hpp
- src/terrama2/core/utility/FilterUtils.cpp
- src/terrama2/core/utility/Service.cpp
- src/terrama2/services/collector/core/Service.cpp
Reverts TerraMA2/terrama2#1898
> Revert "Fix verify compare dates in collector"

- src/terrama2/core/utility/FilterUtils.cpp
- webapp/core/data-model/Filter.js
- webapp/locales/en_US.json
- webapp/locales/es_ES.json
- webapp/locales/pt_BR.json
- webapp/public/javascripts/angular/analysis/controllers/register-update.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/filter.html
- webapp/public/javascripts/angular/wizard.html
Reverts TerraMA2/terrama2#1897
> Revert "Alter Filter to GMT Timezone - Initial Time From Analisys to GMT Timezone"

- src/terrama2/core/data-model/Filter.hpp
- src/terrama2/core/utility/FilterUtils.cpp
- src/terrama2/core/utility/Service.cpp
- src/terrama2/core/utility/TimeUtils.cpp
- src/terrama2/core/utility/TimeUtils.hpp
- src/terrama2/services/collector/core/Service.cpp
- webapp/core/data-model/Filter.js
- webapp/locales/en_US.json
- webapp/locales/es_ES.json
- webapp/locales/pt_BR.json
- webapp/public/javascripts/angular/analysis/controllers/register-update.js
- webapp/public/javascripts/angular/data-series/registration.js
- webapp/public/javascripts/angular/datetimepicker/directive.js
- webapp/public/javascripts/angular/datetimepicker/templates/filterdatetimepicker.html
- webapp/public/javascripts/angular/filter.html
- webapp/public/javascripts/angular/wizard.html
> Fix Date Time Filter Bug

- src/terrama2/impl/DataAccessorFile.cpp
Fix static data filter
**Type:**
**Platform:**
> Fix static data filter

- src/terrama2/core/data-model/Filter.hpp
- src/terrama2/core/utility/FilterUtils.cpp
- src/terrama2/core/utility/Service.cpp
- src/terrama2/services/collector/core/Service.cpp
- webapp/core/DataManager.js
Fix Historical Filter in Analysis
**Type:**
**Platform:**
> Fix Historical Filter in Analysis

- src/terrama2/core/utility/Service.cpp
remove comments
**Type:**
**Platform:**
> remove comments

- webmonitor/config/sample_instances/default.json
- webmonitor/controllers/CheckGridController.js
- webmonitor/controllers/GetAttributesTableController.js
- webmonitor/package.json
- webmonitor/public/javascripts/components/Layers.js
- webmonitor/sockets/Proxy.js
- webmonitor/sockets/State.js
- webmonitor/sockets/ViewsHandler.js
Added ssl configuration
@juan0101 
**Type:**
**Platform:**
> Added ssl configuration

- share/terrama2/semantics/geo-obj-postgis.json
- src/terrama2/impl/DataStoragerTable.cpp
- webapp/locales/pt_BR.json
Implemented feature for when the collector fetches the shape files, delete the files from the table.
@juan0101 
**Type:**
**Platform:**
> Case replace,Truncate table

- src/terrama2/impl/DataStoragerTable.hpp
Implemented feature for when the collector fetches the shape files, delete the files from the table.
@juan0101 
**Type:**
**Platform:**
> Hpp, getStorageOption

- src/terrama2/impl/DataAccessorGeometricObjectOGR.cpp
- src/terrama2/impl/DataStoragerTable.cpp
Fixed Storange, append or replace
@juan0101 
**Type:**
**Platform:**
> Fixed Storange, append or replace

- src/terrama2/impl/DataAccessorGeometricObjectOGR.cpp
- src/terrama2/impl/DataStoragerTable.cpp
Fixed code try
@juan0101 
**Type:**
**Platform:**
> Fixed code try

- webapp/controllers/api/AttributesTable.js
- webapp/core/Enums.js
- webapp/seeders/20202406000000-add-https-data-provider-type.js
- webcomponents/javascripts/src/components/MapDisplay.TerraMA2WebComponents.js
- webmonitor/config/sample_instances/default.json
- webmonitor/config/sample_instances/user_conf.json
- webmonitor/config/sample_instances/user_conf.md
- webmonitor/controllers/CheckGridController.js
- webmonitor/controllers/GetAttributesTableController.js
- webmonitor/core/Application.js
- webmonitor/package.json
- webmonitor/public/javascripts/TerraMA2WebMonitor.js
- webmonitor/public/javascripts/components/MapTools.js
- webmonitor/public/stylesheets/TerraMA2WebMonitor.css
- webmonitor/routes/index.js
- webmonitor/sockets/Proxy.js
- webmonitor/sockets/State.js
- webmonitor/sockets/ViewsHandler.js
- webmonitor/views/index.html
Added some functionalities from branch b4.1.1
**Type:**
**Platform:**
> Added some functionalities from branch b4.1.1

- build/cmake/CMakeLists.txt
- packages/debian-package/deb-terrama2.sh
- webapp/config/settings.json.example
- webapp/locales/en_US.json
- webapp/locales/es_ES.json
Upgraded to version 4.1.1 on cmakelists
@MiguelThiagoAlvarenga @juan0101 
**Type:**
**Platform:**
> Upgraded to version 4.1.1 on cmakelists

- install/release-install.sh
- install/terrama2-ubuntu-16-04-config.sh
- packages/debian-package/deb-terrama2.sh
- scripts/mac/postinst.sh
- scripts/postinst.in
- scripts/prerm.in
- scripts/remove-config.py
Fixed bugs on configuration files
**Type:**
**Platform:**
> Fixed bugs on configuration files

- LINUX-OLD.md
- LINUX.md
- README.md
- helper/Plataforma de Monitoramento Ambiental TerraMA².html
- helper/Plataforma de Monitoramento Ambiental TerraMAý.html
- helper/introduction.html
- install/release-install.sh
- install/terrama2-ubuntu-16-04-config.sh
- packages/debian-package/deb-gtest.sh
- packages/debian-package/deb-helper.sh
- packages/debian-package/deb-terrama2.sh
- webapp/config/settings.json.example
- webapp/locales/en_US.json
- webapp/locales/es_ES.json
- webapp/locales/pt_BR.json
- webmonitor/config/sample_instances/user_conf.md
- webmonitor/locales/en.json
- webmonitor/locales/es.json
- webmonitor/locales/pt.json
Changed version from 4.1.1 to develop on config scripts
**Type:**
**Platform:**
> Changed version from 4.1.1 to develop on config scripts

- LINUX-OLD.md
- LINUX.md
- helper/Plataforma de Monitoramento Ambiental TerraMA².html
- helper/Plataforma de Monitoramento Ambiental TerraMAý.html
- helper/introduction.html
- install/release-install.sh
- install/terrama2-ubuntu-16-04-config.sh
- packages/debian-package/deb-gtest.sh
- packages/debian-package/deb-helper.sh
- packages/debian-package/deb-terrama2.sh
- webapp/locales/en_US.json
- webapp/locales/es_ES.json
- webapp/locales/pt_BR.json
- webmonitor/config/sample_instances/user_conf.md
- webmonitor/locales/en.json
- webmonitor/locales/es.json
- webmonitor/locales/pt.json
- webmonitor/package.json
Changed version from b4.1.1 to b4.1.1-beta on config files
**Type:**
**Platform:**
> Changed version from b4.1.1 to b4.1.1-beta on config files

- packages/debian-package/deb-helper.sh
Changed debian generation control file version
**Type:**
**Platform:**
> Changed debian generation control file version

- install/release-install.sh
Removed release from terrama2 deb download
@juan0101 
**Type:**
**Platform:**
> Removed release from terrama2 deb download

- src/terrama2/core/utility/FilterUtils.cpp
- src/terrama2/core/utility/Service.cpp
Historical date fix bug
**Type:**
**Platform:**
> Historical date fix bug

- webmonitor/controllers/CheckGridController.js
- webmonitor/controllers/GetAttributesTableController.js
- webmonitor/sockets/Proxy.js
- webmonitor/sockets/State.js
- webmonitor/sockets/ViewsHandler.js
Removed ssl modifications
@juan0101 
**Type:**
**Platform:**
> Removed ssl modifications

- src/terrama2/core/utility/Service.cpp
Colector hasBeforeDate Fix
**Type:**
**Platform:**
> Colector hasBeforeDate Fix

- share/terrama2/scripts/sql-functions/vectorial_processing_intersection.sql
- src/terrama2/impl/DataStoragerTable.cpp
- src/terrama2/impl/DataStoragerTable.hpp
- webapp/migrations/20200806000000-create-table-ids-controller.js
Fix vectorial process bug(verification with id)
**Type:**
**Platform:**
> Fix vectorial process bug(verification with id)

- src/terrama2/services/analysis/core/vector-processing/Intersection.cpp
- src/terrama2/services/analysis/core/vector-processing/Intersection.hpp
verify analysis table name
**Type:**
**Platform:**
> verify analysis table name

- webmonitor/app.js
- webmonitor/config/Passport.js
- webmonitor/config/sample_instances/default.json
- webmonitor/controllers/CheckGridController.js
- webmonitor/controllers/GetAttributesTableController.js
- webmonitor/public/javascripts/components/LayerToolbox.js
- webmonitor/public/javascripts/components/Utils.js
- webmonitor/routes/index.js
- webmonitor/sockets/Proxy.js
- webmonitor/sockets/State.js
- webmonitor/sockets/ViewsHandler.js
- webmonitor/utils/common.js
- webmonitor/views/index.html
Add SSL support in TerraMA2 - monitor, webapp
Close #1949 
@
**Type:**
**Platform:**
<details>
*New feature:*
* Item one
* Sub item one
*Enhancement:*
* Item one
* Sub item one
*Bug fix:*
* Item one
* Sub item one
</details>
> Fix webmonitor access public and internal uri to work over HTTPS

- webapp/config/settings.json.example
- webapp/seeders/20190501115200-service-instance-view.js
- webmonitor/sockets/State.js
Removed isSSL variable from State.js and removed geoserver settings from settings.json
**Type:**
**Platform:**
> Removed isSSL variable from State.js and removed geoserver settings from settings.json

- install/release-install.sh
Fixed file check on release-install.sh
@juan0101 
**Type:**
**Platform:**
> Fixed file check on release-install.sh
