build/cmake/terrama2_macros.cmake

Now the folder is generated when the cmake runs.

Fixed the folder generation inside ws_mod_collector_server in terrama2_macros.cmake

---

build/cmake/terrama2_mod_ws_collector_core/CMakeLists.txt
src/terrama2/ws/collector/client/Client.cpp
src/terrama2/ws/collector/client/Client.hpp
src/terrama2/ws/collector/core/Utils.hpp
src/terrama2/ws/collector/core/WebService.hpp
src/terrama2/ws/collector/server/WebService.cpp

Solved error "CMake can not determine linker language for target".
When default, the linker language is setted the language of the files in the library (source files), as there aren't source files in the terrama2_ws_collector_core, the property was passed in "set_target_properties".

Fixed collector core CMakeLists.txt

---

src/terrama2/collector/CurlOpener.cpp
src/terrama2/collector/CurlOpener.hpp
src/terrama2/collector/DataRetrieverFTP.cpp
src/terrama2/collector/DataRetrieverFTP.hpp
src/terrama2/collector/FileOpener.cpp
src/terrama2/collector/FileOpener.hpp
src/terrama2/gui/admin/AdminApp.cpp
src/terrama2/gui/admin/AdminApp.hpp

Ticket #212:
- curl_easy_cleanup not being done everywhere;
- vectorNames_ is being cleaned with a clear, must verify that the files were low and remove if applicable;
- curl is not being cleaned or released:
- use RAII
- destfilepath not being closed:
-  use RAII
- the folder "/ tmp" can not be used this way, it will be different on each operating system. use a string for easy maintenance.
adjustments in the administration module:
- Do not open the same project more than once;
- Moving the mouse to hourglass when creating a database.

Reviewing creation / destruction of objects in the Data FTP Retrieve using the technique RAII

---

src/unittest/core/MockDataRetriever.hpp
src/unittest/core/TsDataAccessorDcpInpe.cpp
src/unittest/core/TsDataAccessorDcpInpe.hpp

Ticket #531 - Review methods const in Mock:
- const methods should use macro MOCK_CONST_METHOD review the use of macros.

Review methods const in Mock

---

build/cmake/terrama2_unittest_core/CMakeLists.txt
src/unittest/core/MockDataSource.hpp
src/unittest/core/TsDataAccessorDcpInpe.cpp
src/unittest/core/TsDataAccessorDcpInpe.hpp

Adjustment MockDataSource and TsDataAccessorDcpInpe:
Adding makeMockDataSource in MockDataSource;
Adding TestFailDataSourceInvalid and TestFailDataSetInvalid in TsDataAccessorDcpInpe;
Adding terralib_mod_ogr in Cmakelist.txt Unittest_core.

Adjustment MockDataSource and TsDataAccessorDcpInpe.

---

webapp/controllers/api/Uri.js
webapp/core/AbstractRequest.js
webapp/core/FtpRequest.js
webapp/core/Utils.js
webapp/public/javascripts/angular/analysis/registration.js

Small fix: adding monitored_object_pk in analysis output data series

---

webapp/bin/www
webapp/config/Database.js
webapp/config/HTTPFactory.js
webapp/config/Sequelize.js
webapp/core/Application.js
webapp/core/DataManager.js
webapp/core/facade/tcp-manager/TcpService.js
webapp/public/javascripts/angular/services/service.js
webapp/public/javascripts/angular/table/templates/table.html

```json
{
"default": {
"ssl": {
"key": "/opt/terrama2/ssl/terrama2-key.pem",
"cert": "/opt/terrama2/ssl/terrama2-cert.pem"
},
"port": 36000,
"db": {...}
}
}
```
**Note** ssl is ```false``` by default.

Webapp: Adding HTTPS support

---

share/terrama2/semantics.json
src/terrama2/impl/DataAccessorFile.cpp
src/terrama2/impl/DataAccessorGrADS.cpp
src/terrama2/impl/DataAccessorGrADS.hpp

- DataAccessorFile and DataAccessorGrADS review
- half-fix Longitude from 0/360 to -180/180 in GrADS files
- details in [#935](https://trac.dpi.inpe.br/terrama2/ticket/935)
- fix GrADS y-axis orientation

fix DataSeries DCP postgis fields

---

src/examples/core/ProcessLogger.cpp
src/terrama2/core/utility/ProcessLogger.cpp
src/terrama2/core/utility/ProcessLogger.hpp
src/terrama2/impl/DataAccessorGrADS.cpp
src/terrama2/services/alert/core/RunAlert.cpp
src/terrama2/services/analysis/core/AnalysisExecutor.cpp
src/terrama2/services/analysis/core/BaseContext.cpp
src/terrama2/services/analysis/core/BaseContext.hpp
src/terrama2/services/analysis/core/ContextManager.cpp
src/terrama2/services/analysis/core/MonitoredObjectContext.cpp
src/terrama2/services/analysis/core/dcp/Operator.cpp
src/terrama2/services/analysis/core/dcp/history/Operator.cpp
src/terrama2/services/analysis/core/dcp/influence/Operator.cpp
src/terrama2/services/analysis/core/grid/Operator.cpp
src/terrama2/services/analysis/core/grid/history/Operator.cpp
src/terrama2/services/analysis/core/grid/zonal/Operator.cpp
src/terrama2/services/analysis/core/grid/zonal/forecast/Operator.cpp
src/terrama2/services/analysis/core/grid/zonal/history/Operator.cpp
src/terrama2/services/analysis/core/grid/zonal/history/accum/Operator.cpp
src/terrama2/services/analysis/core/grid/zonal/history/prec/Operator.cpp
src/terrama2/services/analysis/core/occurrence/Operator.cpp
src/terrama2/services/analysis/core/python/PythonInterpreter.cpp
src/terrama2/services/appserver/main.cpp
src/terrama2/services/collector/core/Service.cpp
src/terrama2/services/view/core/Service.cpp
src/terrama2/services/view/core/data-access/Geoserver.cpp
src/unittest/core/TsProcessLogger.cpp

Using binary mask to overwrite CTL configuration for remote data
Refactoring logger class
Logging no data as warning

Using binary mask to overwrite CTL configuration for remote data 

---

src/terrama2/core/utility/Utils.cpp
src/terrama2/core/utility/Utils.hpp
src/terrama2/services/analysis/core/AnalysisExecutor.cpp
src/terrama2/services/analysis/core/AnalysisExecutor.hpp
src/terrama2/services/analysis/core/BaseContext.cpp
src/terrama2/services/analysis/core/BaseContext.hpp
src/terrama2/services/analysis/core/ContextManager.cpp
src/terrama2/services/analysis/core/ContextManager.hpp
src/terrama2/services/analysis/core/MonitoredObjectContext.cpp
src/terrama2/services/analysis/core/dcp/Operator.cpp
src/terrama2/services/analysis/core/dcp/history/Operator.cpp
src/terrama2/services/analysis/core/dcp/influence/Operator.cpp
src/terrama2/services/analysis/core/grid/Operator.cpp
src/terrama2/services/analysis/core/grid/history/Operator.cpp
src/terrama2/services/analysis/core/grid/zonal/Operator.cpp
src/terrama2/services/analysis/core/grid/zonal/forecast/Operator.cpp
src/terrama2/services/analysis/core/grid/zonal/history/Operator.cpp
src/terrama2/services/analysis/core/grid/zonal/history/accum/Operator.cpp
src/terrama2/services/analysis/core/grid/zonal/history/prec/Operator.cpp
src/terrama2/services/analysis/core/occurrence/Operator.cpp
src/terrama2/services/analysis/core/python/PythonInterpreter.cpp
webapp/locales/en.json

- Changes in band identification for forecast operators,
- analysis log messages now have a type (error, warning...)
- Fix log messages call in forecast operators

Forecast operators and using error type in log messages

---

src/terrama2/core/utility/ProcessLogger.cpp
src/terrama2/core/utility/ProcessLogger.hpp
src/terrama2/core/utility/Service.cpp
src/terrama2/services/view/core/MapsServer.hpp
src/terrama2/services/view/core/Service.cpp
src/terrama2/services/view/core/Service.hpp
src/terrama2/services/view/core/ViewLogger.hpp
src/terrama2/services/view/core/data-access/Geoserver.cpp
src/terrama2/services/view/core/data-access/Geoserver.hpp

- Using a copy of logger object to avoid changes during the service job;
- Checking  if the logger has a valid connection to data source, if not, don't execute any logger operation, stop the current job and don't add jobs to queue
- The service will remaining running with a invalid logger, but will not execute jobs until has a valid logger;
If approved, I will replicate this to the others services.

Handling the Process logger errors in View Service

---

src/terrama2/impl/DataAccessorFile.cpp

When Terralib can't open a file we get an empty timestamp, ignore and continue

Fix: continue when error opening file

---

webmonitor/public/javascripts/utils/calendar.js
webmonitor/views/index.html

The "new" status didn't change to "working" status when click to see the layer
The calendar component was not opened with the latest selected dates

Web monitor calendar and status icon fixes

---

webapp/core/DataManager.js
webapp/core/data-model/Alert.js
webapp/core/facade/Alert.js
webapp/models/Alert.js
webapp/models/Schedule.js
webapp/public/javascripts/angular/alerts/controllers/alert-register-update.js
webapp/public/javascripts/angular/alerts/controllers/index.js
webapp/sockets/ImportExport.js
webapp/views/configuration/alert.html

Options to select schedule type in Alert
Need update the database with the following script:
```
ALTER TABLE terrama2.alerts ADD COLUMN schedule_id INTEGER;
ALTER TABLE terrama2.alerts_schedule_id_fkey ADD CONSTRAINT alerts_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES terrama2.schedules (id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE terrama2.alerts ADD COLUMN schedule_type INTEGER;
UPDATE terrama2.alerts SET schedule_type = 4;
```

Schedule option in Alert

---

src/terrama2/services/analysis/core/grid/zonal/Operator.cpp
src/terrama2/services/analysis/core/grid/zonal/Utils.hpp
src/terrama2/services/analysis/core/grid/zonal/forecast/Operator.cpp
src/terrama2/services/analysis/core/grid/zonal/forecast/accum/Operator.cpp
src/terrama2/services/analysis/core/grid/zonal/history/Operator.cpp
src/terrama2/services/analysis/core/occurrence/zonal/Operator.cpp

when using a monitored object with invalid geometries return nan but continue the analysis

Continue analysis even with invalid geometries

---

build/cmake/CMakeLists.txt

If Gmock isn't found disable the examples and unit-test

Create dependency between example, unit-test and GMock,

---

src/terrama2/services/view/core/DataManager.cpp
src/terrama2/services/view/core/DataManager.hpp
src/terrama2/services/view/core/MapsServer.hpp
src/terrama2/services/view/core/Service.cpp
src/terrama2/services/view/core/Service.hpp
src/terrama2/services/view/core/Utils.cpp
src/terrama2/services/view/core/Utils.hpp
src/terrama2/services/view/core/View.hpp
src/terrama2/services/view/core/data-access/Geoserver.cpp
src/terrama2/services/view/core/data-access/Geoserver.hpp

These changes improves View Service management. Now, the auto-cleanup environment such GeoServer workspace, properties files and table management are working properly.  The view are stored in database as `view` + `viewID` to avoid unnecessary table creation whenever view name changed and their files contains absolute path to data file.
Tasks:
- GeoServer & Properties files;
- View Table.

View Service minor changes

---

src/terrama2/services/view/core/data-access/Geoserver.cpp

Sometimes, the GeoServer does not recognizes analysis result SRID (even supporting) and compute incorrect extent. This change sets this configuration manually to avoid GeoServer auto configure.

Fix View Monitored Object Result SRID

---

share/terrama2/semantics/occurrence-postgis.json
src/terrama2/impl/DataAccessorOccurrenceWfp.cpp
src/terrama2/impl/DataAccessorPostGIS.cpp
src/terrama2/impl/DataStoragerTable.cpp

- The occurrence postgis semantics wasn't requiring a timestamp and a geometry column.
- When transforming a geometry in UTM projection there were cases where the data could be out of the utm zone, now everything is transformed to EPSG:4326 (latlong-wgs84)
- Including Timezone to occurrence wfp to fix geoserver bug

Occurrence postgis timestamp column

---

src/terrama2/core/data-access/DataAccessor.cpp
src/terrama2/core/utility/GeoUtils.cpp
src/terrama2/core/utility/GeoUtils.hpp
src/terrama2/core/utility/ProcessLogger.cpp
src/terrama2/impl/DataAccessorFile.cpp
src/terrama2/impl/DataAccessorFile.hpp
src/terrama2/impl/DataStoragerDCPPostGIS.cpp
src/terrama2/services/collector/core/IntersectionOperation.cpp

Update positions table.
Old behavior:
remove and recreate the table every time
New behavior:
Update the table with new DCP
Known issues:
- Old positions are not being updated
!Important!:
Removed DCP are kept in the table for old analysis results.

Fix dcp postions table

---

.gitignore
packages/debian-package/deb-helper.sh

* The script creates a simple debian package that installs the `helper` folder.
* If necessary the installation path can be changed by changing the `TM_FOLDER` variable.

Adding helper debian package script

---

src/terrama2/impl/DataAccessorOccurrenceWfp.cpp
src/terrama2/impl/DataAccessorOccurrenceWfp.hpp
src/terrama2/impl/DataStoragerTable.cpp
src/terrama2/impl/DataStoragerTable.hpp
src/unittest/core/TsDataAccessorOccurrenceWfp.cpp

Copy the DataSetTyoe without using the clone method, the properties won't inherit modifiers like 'not null'.
Properties removed from DataAcessorWFP:
- lat
- long
- hora
- data

Copy datasettype, romove unecessary properties from WFP

---

webmonitor/public/javascripts/TerraMA2WebMonitor.js

When clicking to show occurrence points, both image and description are not display properly. The Webmonitor is not word wrapping the content.
@janosimas 
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix max-width size for images in webmonitor
* Fix word wrap in webmonitor
</details>

Fix Webmonitor feature box

---

webapp/public/javascripts/angular/interpolator/controllers/interpolator-register-update.js
webapp/public/javascripts/angular/interpolator/templates/inter-parameter.html

In Interpolator Registration, the user must fill `Valid time unit` with number and a time property (`s` for seconds, `m` for minutes , `h` for hours or `d` for days). It should be similar Schedule feature with Time properties in combobox and a number field.
@janosimas 
**Type:**
**Platform:**
<details>
*Enhancement:*
* Fix interpolator time unit with combobox and number field
</details>

Fix interpolator time unit

---

webapp/core/DataManager.js

Sometimes TerraMA2 is not able to save *RegisteredView*. It seems to be related with transaction operation in the method `addRegisteredView` of DataManager. The argument `options` msut be passed through `addView` to sequelize be capable of proceed with transaction.
@janosimas 
**Type:**
**Platform:**
**Ticket:**
<details>
*Bug fix:*
* Fix process to generate registered view using sequelize transactor
</details>

Fix process to generate registered view using Transactor

---

webmonitor/controllers/LoginController.js
webmonitor/gruntfile.js
webmonitor/package-lock.json
webmonitor/package.json
webmonitor/public/javascripts/TerraMA2WebMonitor.js
webmonitor/public/javascripts/components/Login.js
webmonitor/public/javascripts/components/State.js
webmonitor/public/javascripts/components/Utils.js
webmonitor/sockets/ViewsHandler.js

A private view can be accessed by a user without authentication. It seems related token handling on webmonitor.
The temporary solution is to keep authority token in browser session whenever user tries to login, keeping the consistency with back-end. But is should be re-factored in the future to adopt the architecture of OAuth2 tokens for security and scalable environments.
@janosimas 
**Type:**
**Platform:**
**Ticket:**
<details>
*Bug fix:*
* Fix view permission on Webmonitor
</details>

Fix view permission on webmonitor (temporary)

---

Changelog.md
src/terrama2/core/utility/FilterUtils.cpp
src/terrama2/core/utility/FilterUtils.hpp
webapp/public/javascripts/angular/data-series/services.js

Create a new tag for regex in TerraMA2 masks.
Regex should be enclosed by %( and )%.
@raphaelrpl 
**Type:**
**Platform:**
<details>
*New feature:*
- Allow regex in the masks.
</details>

TerraMA2 regex expression

---

webapp/models/Collector.js
webapp/models/index.js

When user performs activate/deactivate a data series with collector, the project id is not set and the terrama2 c++ service stuck due JSON is not valid.
The solution is to customize *beforeFind* and *afterFind* hooks of ORM to ensure that **project_id** is always set.
@janosimas
**Type:**
**Platform:**
**Ticket:**
<details>
*Bug fix:*
* Fix project identifier in collector
</details>

Fix project identifier in collector

---

webapp/core/DataManager.js

The *RegisteredView* URI is not being updated when a view already exists. In this way, the user must manually remove row value in database to these changes make effect.
This patch allows to update automatically the URI when a view is executed.
@janosimas 
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix registered view update uri
</details>

Fix registered view update uri

---

Changelog.md
src/terrama2/services/view/core/data-access/Geoserver.cpp

Fix error creating view when the layer is removed from geoserver
**Type:**
**Platform:**
<details>
*Bug fix:*
- Fix error creating view when the layer is removed from geoserver
</details>

recreate layer when deleted from geoserver

---

webapp/public/javascripts/angular/projects/controllers/list.js

The swipe button of Project List not working. It seems like not implemented yet. 
@janosimas 
**Type:**
**Platform:**
<details>
*Bug fix:*
* Disable swipe button to activate/deactivate project and own dependencies 
</details>

Disable swipe button to activate/deactivate projects (temporary)

---

webapp/controllers/configuration/ImportStaticFiles.js
webapp/core/Exportation.js
webapp/core/ShapeImporter.js
webapp/package-lock.json
webapp/package.json
webapp/yarn.lock

When the user upload a zip file that contains a file with size 0, the nodejs hangs on. This bug is related with dependency [unzip2 - Issue 2](https://github.com/glebdmitriew/node-unzip-2/issues/2). This patch changes the dependency to [`adm-zip`](https://github.com/cthackers/adm-zip). It also improves Shapefile interface.
**Type:**
**Platform:**
<details>
*Bug fix:*
* Fix Shapefile import when size is 0
</details>

Fix Shapefile import when size is 0

---

src/terrama2/impl/DataAccessorCSV.cpp

Error in importing burned and custom occurrence data from CVS file
@
**Type:**
**Platform:**
<details>
*New feature:*
* Item one
* Sub item one
*Enhancement:*
* Item one
* Sub item one
*Bug fix:*
* Item one
* Sub item one
</details>
The error occurred because the search was done before the remotion. The removal modifies the value of the position of attribute.

Correction of ocurrence importations from CVS files

---

src/terrama2/impl/DataAccessorCSV.cpp
src/terrama2/services/collector/core/Service.cpp
webapp/public/javascripts/angular/data-series/components/csvFormat.js
webapp/public/javascripts/angular/data-series/registration.js
webapp/public/javascripts/angular/data-series/templates/csvFormat.html
webapp/public/javascripts/angular/wizard.html

Include a field `Delimiter` to customize CSV importation on database, since some of providers define **comma** or even **semicolon** on CSV files.
**Type:**
**Platform:**
<details>
*Enhancement:*
* Include CSV delimiter on semantics Occurrence CSV
</details>

Include CSV delimiter on semantics Occurrence CSV

---

webmonitor/public/javascripts/TerraMA2WebMonitor.js

Add sentinel 2 in template maps - webmonitor
**Type:**
**Platform:**
<details>
*Enhancement:*
* Add sentinel 2 in template maps - webmonitor
</details>

Add sentinel 2 in template maps - webmonitor

---

src/terrama2/services/analysis/core/GridContext.cpp
src/terrama2/services/analysis/core/GridContext.hpp
src/terrama2/services/analysis/core/dcp/zonal/Operator.cpp
src/terrama2/services/analysis/core/python/PythonInterpreter.cpp
src/terrama2/services/analysis/core/utility/Utils.cpp
src/terrama2/services/analysis/core/utility/Utils.hpp

1.It was using string to store the values ​​of the parameters of creating a new grid, it was changed to use double. It was truncating the values, generating disagreements.
2.Settings in handling error messages.
@
**Type:**
**Platform:**
<details>
*New feature:*
* Item one
* Sub item one
*Enhancement:*
* Item one
* Sub item one
*Bug fix:*
* Item one
* Sub item one
</details>

Parameters of the analysis output image (Sample) and error messages

---

webapp/controllers/api/DataSeries.js
webapp/core/facade/Collector.js

Minor bug - force CollectorInputOutput on Collector instance when DCP updates
**Type:**
**Platform:**
<details>
*Bug fix:*
* Minor bug - force CollectorInputOutput on Collector instance when DCP updates
</details>

Minor bug - force CollectorInputOutput on Collector instance when DCP updates

---

webmonitor/public/javascripts/TerraMA2WebMonitor.js

Fixed bug that was making the selected layers, from 'user_conf.json', been activated when another layer was updated
@juan0101 
**Type:**
**Platform:**

Fixed bug on selected layers user_conf.json

---

webmonitor/routes/index.js

Fix merge with b4.1.1 - passing ``webmonitorHostConfig`` to browser in order to avoid connect default port.
#1949 
**Type:**
**Platform:**
<details>
*New feature:*
* Item one
* Sub item one
*Enhancement:*
* Item one
* Sub item one
*Bug fix:*
* Item one
* Sub item one
</details>

Fix merge with b4.1.1 - passing webmonitorHostConfig to browser

---

install/release-install.sh

Removed prompt from ssh-keygen and fixed terralib tar.gz name on release-install.sh
@juan0101 
**Type:**
**Platform:**
<details>
*New feature:*
* Item one
* Sub item one
*Enhancement:*
* Item one
* Sub item one
*Bug fix:*
* Item one
* Sub item one
</details>

Removed prompt from ssh-keygen and fixed terralib tar.gz name on release-install.sh
